// packages/@visual-json/svelte/src/components/VisualJson.svelte
<script lang="ts">
	import { setContext } from 'svelte';
	import type { Snippet } from 'svelte';
	import {
		fromJson,
		toJson,
		History,
		searchNodes,
		getAncestorIds,
		type JsonValue,
		type JsonSchema,
		type TreeState,
		type TreeNode,
		type SearchMatch
	} from '@visual-json/core';
	import { collectAllIds, getVisibleNodes } from '@internal/ui';
	import { STUDIO_KEY, type StudioState, type StudioActions } from '../context.js';
	import { computeRangeIds } from '../selection-utils.js';

	interface Props {
		value: JsonValue;
		schema?: JsonSchema | null;
		onchange?: (value: JsonValue) => void;
		children?: Snippet;
	}

	let { value, schema = null, onchange, children }: Props = $props();

	let tree = $state<TreeState>(fromJson(value));
	let focusedNodeId = $state<string | null>(null);
	let selectedNodeIds = $state<Set<string>>(new Set());
	let anchorNodeId = $state<string | null>(null);
	let drillDownNodeId = $state<string | null>(null);
	let expandedNodeIds = $state<Set<string>>(new Set([tree.root.id]));

	let visibleNodesOverride: TreeNode[] | null = null;
	let history = new History();
	let historyVersion = $state(0);

	let searchQuery = $state('');
	let searchMatches = $state<SearchMatch[]>([]);
	let searchMatchIndex = $state(0);

	let isInternalChange = false;

	history.push(tree);

	function focusSelectAndDrillDown(nodeId: string | null) {
		focusedNodeId = nodeId;
		selectedNodeIds = nodeId ? new Set([nodeId]) : new Set();
		anchorNodeId = nodeId;
		drillDownNodeId = nodeId;
	}

	// Sync external value changes
	$effect(() => {
		const v = value;
		if (isInternalChange) {
			isInternalChange = false;
			return;
		}
		const newTree = fromJson(v);
		tree = newTree;
		expandedNodeIds = new Set([newTree.root.id]);
		focusSelectAndDrillDown(null);
		history = new History();
		history.push(newTree);
		historyVersion++;
		searchQuery = '';
		searchMatches = [];
		searchMatchIndex = 0;
	});

	// Update search results when tree changes
	$effect(() => {
		const currentTree = tree;
		const query = searchQuery;
		if (!query.trim()) return;
		const matches = searchNodes(currentTree, query);
		searchMatches = matches;
		searchMatchIndex = Math.min(searchMatchIndex, Math.max(matches.length - 1, 0));
	});

	function setTree(newTree: TreeState) {
		tree = newTree;
		history.push(newTree);
		historyVersion++;
		isInternalChange = true;
		onchange?.(toJson(newTree.root));
	}

	function undo() {
		const prev = history.undo();
		if (prev) {
			tree = prev;
			historyVersion++;
			isInternalChange = true;
			onchange?.(toJson(prev.root));
		}
	}

	function redo() {
		const next = history.redo();
		if (next) {
			tree = next;
			historyVersion++;
			isInternalChange = true;
			onchange?.(toJson(next.root));
		}
	}

	function handleKeyDown(e: KeyboardEvent) {
		const mod = e.metaKey || e.ctrlKey;
		if (mod && e.key === 'z' && !e.shiftKey) {
			e.preventDefault();
			undo();
		} else if (mod && e.key === 'z' && e.shiftKey) {
			e.preventDefault();
			redo();
		} else if (mod && e.key === 'y') {
			e.preventDefault();
			redo();
		}
	}

	$effect(() => {
		document.addEventListener('keydown', handleKeyDown);
		return () => document.removeEventListener('keydown', handleKeyDown);
	});

	const visibleNodes = $derived(getVisibleNodes(tree.root, (id) => expandedNodeIds.has(id)));

	const stateCtx: StudioState = {
		get tree() {
			return tree;
		},
		get focusedNodeId() {
			return focusedNodeId;
		},
		get selectedNodeIds() {
			return selectedNodeIds;
		},
		get anchorNodeId() {
			return anchorNodeId;
		},
		get drillDownNodeId() {
			return drillDownNodeId;
		},
		get expandedNodeIds() {
			return expandedNodeIds;
		},
		get schema() {
			return schema ?? null;
		},
		get searchQuery() {
			return searchQuery;
		},
		get searchMatches() {
			return searchMatches;
		},
		get searchMatchIndex() {
			return searchMatchIndex;
		},
		get searchMatchNodeIds() {
			return new Set(searchMatches.map((m) => m.nodeId));
		},
		get canUndo() {
			return historyVersion >= 0 && history.canUndo;
		},
		get canRedo() {
			return historyVersion >= 0 && history.canRedo;
		}
	};

	const actions: StudioActions = {
		setTree,
		selectNode(nodeId) {
			focusedNodeId = nodeId;
			selectedNodeIds = nodeId ? new Set([nodeId]) : new Set();
			anchorNodeId = nodeId;
		},
		selectAndDrillDown: focusSelectAndDrillDown,
		toggleNodeSelection(nodeId) {
			const next = new Set(selectedNodeIds);
			if (next.has(nodeId)) {
				next.delete(nodeId);
			} else {
				next.add(nodeId);
			}
			selectedNodeIds = next;
			if (next.size === 0) {
				focusedNodeId = null;
				anchorNodeId = null;
			} else {
				focusedNodeId = nodeId;
				anchorNodeId = nodeId;
			}
		},
		selectNodeRange(toNodeId) {
			const nodes = visibleNodesOverride ?? visibleNodes;
			const anchor = anchorNodeId;
			if (!anchor) {
				focusedNodeId = toNodeId;
				selectedNodeIds = new Set([toNodeId]);
				anchorNodeId = toNodeId;
				return;
			}
			const rangeIds = computeRangeIds(nodes, anchor, toNodeId);
			if (!rangeIds) {
				focusedNodeId = toNodeId;
				selectedNodeIds = new Set([toNodeId]);
				anchorNodeId = toNodeId;
				return;
			}
			selectedNodeIds = rangeIds;
			focusedNodeId = toNodeId;
		},
		setSelection(focusedId, newSelectedIds, newAnchorId) {
			focusedNodeId = focusedId;
			selectedNodeIds = newSelectedIds;
			anchorNodeId = newAnchorId;
		},
		setVisibleNodesOverride(nodes) {
			visibleNodesOverride = nodes;
		},
		drillDown(nodeId) {
			drillDownNodeId = nodeId;
		},
		toggleExpand(nodeId) {
			const next = new Set(expandedNodeIds);
			if (next.has(nodeId)) next.delete(nodeId);
			else next.add(nodeId);
			expandedNodeIds = next;
		},
		expandNode(nodeId) {
			expandedNodeIds = new Set([...expandedNodeIds, nodeId]);
		},
		collapseNode(nodeId) {
			const next = new Set(expandedNodeIds);
			next.delete(nodeId);
			expandedNodeIds = next;
		},
		expandAll() {
			expandedNodeIds = new Set(collectAllIds(tree.root));
		},
		collapseAll() {
			expandedNodeIds = new Set([tree.root.id]);
		},
		undo,
		redo,
		setSearchQuery(query) {
			searchQuery = query;
			if (!query.trim()) {
				searchMatches = [];
				searchMatchIndex = 0;
				return;
			}
			const matches = searchNodes(tree, query);
			searchMatches = matches;
			searchMatchIndex = 0;
			if (matches.length > 0) {
				const ancestors = getAncestorIds(
					tree,
					matches.map((m) => m.nodeId)
				);
				const next = new Set(expandedNodeIds);
				for (const id of ancestors) next.add(id);
				expandedNodeIds = next;
				focusSelectAndDrillDown(matches[0].nodeId);
			}
		},
		nextSearchMatch() {
			if (searchMatches.length === 0) return;
			const nextIdx = (searchMatchIndex + 1) % searchMatches.length;
			searchMatchIndex = nextIdx;
			focusSelectAndDrillDown(searchMatches[nextIdx].nodeId);
		},
		prevSearchMatch() {
			if (searchMatches.length === 0) return;
			const prevIdx = (searchMatchIndex - 1 + searchMatches.length) % searchMatches.length;
			searchMatchIndex = prevIdx;
			focusSelectAndDrillDown(searchMatches[prevIdx].nodeId);
		}
	};

	setContext(STUDIO_KEY, { state: stateCtx, actions });
</script>

{@render children?.()}

// packages/@visual-json/react/src/visual-json.tsx
import {
  useState,
  useCallback,
  useMemo,
  useEffect,
  useRef,
  type ReactNode,
} from "react";
import {
  fromJson,
  toJson,
  History,
  searchNodes,
  getAncestorIds,
  type JsonValue,
  type JsonSchema,
  type TreeState,
  type TreeNode,
  type SearchMatch,
} from "@visual-json/core";
import { collectAllIds, getVisibleNodes } from "@internal/ui";
import { StudioContext, type StudioState, type StudioActions } from "./context";
import { computeRangeIds } from "./selection-utils";

export interface VisualJsonProps {
  value: JsonValue;
  onChange?: (value: JsonValue) => void;
  schema?: JsonSchema | null;
  children: ReactNode;
}

export function VisualJson({
  value,
  onChange,
  schema,
  children,
}: VisualJsonProps) {
  const [tree, setTreeState] = useState<TreeState>(() => fromJson(value));
  const [focusedNodeId, setFocusedNodeId] = useState<string | null>(null);
  const [selectedNodeIds, setSelectedNodeIdsState] = useState<Set<string>>(
    () => new Set<string>(),
  );
  const selectedNodeIdsRef = useRef<Set<string>>(new Set());
  const setSelectedNodeIds = useCallback((ids: Set<string>) => {
    selectedNodeIdsRef.current = ids;
    setSelectedNodeIdsState(ids);
  }, []);
  const anchorNodeIdRef = useRef<string | null>(null);
  const [anchorNodeId, setAnchorNodeIdState] = useState<string | null>(null);
  const [drillDownNodeId, setDrillDownNodeId] = useState<string | null>(null);
  const [expandedNodeIds, setExpandedNodeIds] = useState<Set<string>>(
    () => new Set([tree.root.id]),
  );

  const setAnchorNodeId = useCallback((id: string | null) => {
    anchorNodeIdRef.current = id;
    setAnchorNodeIdState(id);
  }, []);

  const focusSelectAndDrillDown = useCallback(
    (nodeId: string | null) => {
      setFocusedNodeId(nodeId);
      setSelectedNodeIds(nodeId ? new Set([nodeId]) : new Set<string>());
      setAnchorNodeId(nodeId);
      setDrillDownNodeId(nodeId);
    },
    [setSelectedNodeIds, setAnchorNodeId],
  );

  const visibleNodes = useMemo(
    () => getVisibleNodes(tree.root, (id) => expandedNodeIds.has(id)),
    [tree.root, expandedNodeIds],
  );

  const visibleNodesOverrideRef = useRef<TreeNode[] | null>(null);

  const setVisibleNodesOverride = useCallback((nodes: TreeNode[] | null) => {
    visibleNodesOverrideRef.current = nodes;
  }, []);

  const historyRef = useRef<History>(new History());
  const isInternalChange = useRef(false);
  const hasMounted = useRef(false);
  const [canUndo, setCanUndo] = useState(false);
  const [canRedo, setCanRedo] = useState(false);

  const [searchQuery, setSearchQueryState] = useState("");
  const [searchMatches, setSearchMatches] = useState<SearchMatch[]>([]);
  const [searchMatchIndex, setSearchMatchIndex] = useState(0);
  const [searchMatchNodeIds, setSearchMatchNodeIds] = useState<Set<string>>(
    new Set(),
  );

  useEffect(() => {
    historyRef.current.push(tree);
    setCanUndo(historyRef.current.canUndo);
    setCanRedo(historyRef.current.canRedo);
  }, []);

  useEffect(() => {
    if (!hasMounted.current) {
      hasMounted.current = true;
      return;
    }
    if (isInternalChange.current) {
      isInternalChange.current = false;
      return;
    }
    const newTree = fromJson(value);
    setTreeState(newTree);
    setExpandedNodeIds(new Set([newTree.root.id]));
    focusSelectAndDrillDown(null);
    historyRef.current = new History();
    historyRef.current.push(newTree);
    setCanUndo(false);
    setCanRedo(false);
    setSearchQueryState("");
    setSearchMatches([]);
    setSearchMatchIndex(0);
    setSearchMatchNodeIds(new Set());
  }, [value]);

  const setTree = useCallback(
    (newTree: TreeState) => {
      setTreeState(newTree);
      historyRef.current.push(newTree);
      setCanUndo(historyRef.current.canUndo);
      setCanRedo(historyRef.current.canRedo);
      isInternalChange.current = true;
      onChange?.(toJson(newTree.root));
    },
    [onChange],
  );

  const undo = useCallback(() => {
    const prev = historyRef.current.undo();
    if (prev) {
      setTreeState(prev);
      setCanUndo(historyRef.current.canUndo);
      setCanRedo(historyRef.current.canRedo);
      isInternalChange.current = true;
      onChange?.(toJson(prev.root));
    }
  }, [onChange]);

  const redo = useCallback(() => {
    const next = historyRef.current.redo();
    if (next) {
      setTreeState(next);
      setCanUndo(historyRef.current.canUndo);
      setCanRedo(historyRef.current.canRedo);
      isInternalChange.current = true;
      onChange?.(toJson(next.root));
    }
  }, [onChange]);

  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      const mod = e.metaKey || e.ctrlKey;
      if (mod && e.key === "z" && !e.shiftKey) {
        e.preventDefault();
        undo();
      } else if (mod && e.key === "z" && e.shiftKey) {
        e.preventDefault();
        redo();
      } else if (mod && e.key === "y") {
        e.preventDefault();
        redo();
      }
    }

    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [undo, redo]);

  const selectNode = useCallback(
    (nodeId: string | null) => {
      setFocusedNodeId(nodeId);
      setSelectedNodeIds(nodeId ? new Set([nodeId]) : new Set<string>());
      setAnchorNodeId(nodeId);
    },
    [setSelectedNodeIds, setAnchorNodeId],
  );

  const selectAndDrillDown = focusSelectAndDrillDown;

  const toggleNodeSelection = useCallback(
    (nodeId: string) => {
      const next = new Set(selectedNodeIdsRef.current);
      if (next.has(nodeId)) {
        next.delete(nodeId);
      } else {
        next.add(nodeId);
      }
      setSelectedNodeIds(next);
      if (next.size === 0) {
        setFocusedNodeId(null);
        setAnchorNodeId(null);
      } else {
        setFocusedNodeId(nodeId);
        setAnchorNodeId(nodeId);
      }
    },
    [setSelectedNodeIds, setAnchorNodeId],
  );

  const selectNodeRange = useCallback(
    (toNodeId: string) => {
      const nodes = visibleNodesOverrideRef.current ?? visibleNodes;
      const anchor = anchorNodeIdRef.current;
      if (!anchor) {
        setFocusedNodeId(toNodeId);
        setSelectedNodeIds(new Set([toNodeId]));
        setAnchorNodeId(toNodeId);
        return;
      }
      const rangeIds = computeRangeIds(nodes, anchor, toNodeId);
      if (!rangeIds) {
        setFocusedNodeId(toNodeId);
        setSelectedNodeIds(new Set([toNodeId]));
        setAnchorNodeId(toNodeId);
        return;
      }
      setSelectedNodeIds(rangeIds);
      setFocusedNodeId(toNodeId);
    },
    [visibleNodes, setSelectedNodeIds, setAnchorNodeId],
  );

  const setSelection = useCallback(
    (
      focusedId: string | null,
      newSelectedIds: Set<string>,
      newAnchorId: string | null,
    ) => {
      setFocusedNodeId(focusedId);
      setSelectedNodeIds(newSelectedIds);
      setAnchorNodeId(newAnchorId);
    },
    [setSelectedNodeIds, setAnchorNodeId],
  );

  const drillDown = useCallback((nodeId: string | null) => {
    setDrillDownNodeId(nodeId);
  }, []);

  const toggleExpand = useCallback((nodeId: string) => {
    setExpandedNodeIds((prev) => {
      const next = new Set(prev);
      if (next.has(nodeId)) next.delete(nodeId);
      else next.add(nodeId);
      return next;
    });
  }, []);

  const expandNode = useCallback((nodeId: string) => {
    setExpandedNodeIds((prev) => {
      const next = new Set(prev);
      next.add(nodeId);
      return next;
    });
  }, []);

  const collapseNode = useCallback((nodeId: string) => {
    setExpandedNodeIds((prev) => {
      const next = new Set(prev);
      next.delete(nodeId);
      return next;
    });
  }, []);

  const expandAll = useCallback(() => {
    const allIds = collectAllIds(tree.root);
    setExpandedNodeIds(new Set(allIds));
  }, [tree]);

  const collapseAll = useCallback(() => {
    setExpandedNodeIds(new Set([tree.root.id]));
  }, [tree]);

  const setSearchQuery = useCallback(
    (query: string) => {
      setSearchQueryState(query);
      if (!query.trim()) {
        setSearchMatches([]);
        setSearchMatchIndex(0);
        setSearchMatchNodeIds(new Set());
        return;
      }
      const matches = searchNodes(tree, query);
      setSearchMatches(matches);
      setSearchMatchIndex(0);
      const matchIds = new Set(matches.map((m) => m.nodeId));
      setSearchMatchNodeIds(matchIds);

      if (matches.length > 0) {
        const firstId = matches[0].nodeId;
        const ancestors = getAncestorIds(
          tree,
          matches.map((m) => m.nodeId),
        );
        setExpandedNodeIds((prev) => {
          const next = new Set(prev);
          for (const id of ancestors) next.add(id);
          return next;
        });
        focusSelectAndDrillDown(firstId);
      }
    },
    [tree],
  );

  const nextSearchMatch = useCallback(() => {
    if (searchMatches.length === 0) return;
    const nextIdx = (searchMatchIndex + 1) % searchMatches.length;
    setSearchMatchIndex(nextIdx);
    focusSelectAndDrillDown(searchMatches[nextIdx].nodeId);
  }, [searchMatches, searchMatchIndex, focusSelectAndDrillDown]);

  const prevSearchMatch = useCallback(() => {
    if (searchMatches.length === 0) return;
    const prevIdx =
      (searchMatchIndex - 1 + searchMatches.length) % searchMatches.length;
    setSearchMatchIndex(prevIdx);
    focusSelectAndDrillDown(searchMatches[prevIdx].nodeId);
  }, [searchMatches, searchMatchIndex, focusSelectAndDrillDown]);

  useEffect(() => {
    if (!searchQuery.trim()) return;
    const matches = searchNodes(tree, searchQuery);
    setSearchMatches(matches);
    setSearchMatchIndex((prev) =>
      Math.min(prev, Math.max(matches.length - 1, 0)),
    );
    setSearchMatchNodeIds(new Set(matches.map((m) => m.nodeId)));
  }, [tree]);

  const state: StudioState = useMemo(
    () => ({
      tree,
      focusedNodeId,
      selectedNodeIds,
      anchorNodeId,
      drillDownNodeId,
      expandedNodeIds,
      schema: schema ?? null,
      searchQuery,
      searchMatches,
      searchMatchIndex,
      searchMatchNodeIds,
    }),
    [
      tree,
      focusedNodeId,
      selectedNodeIds,
      anchorNodeId,
      drillDownNodeId,
      expandedNodeIds,
      schema,
      searchQuery,
      searchMatches,
      searchMatchIndex,
      searchMatchNodeIds,
    ],
  );

  const actions: StudioActions = useMemo(
    () => ({
      setTree,
      selectNode,
      selectAndDrillDown,
      toggleNodeSelection,
      selectNodeRange,
      setSelection,
      setVisibleNodesOverride,
      drillDown,
      toggleExpand,
      expandNode,
      collapseNode,
      expandAll,
      collapseAll,
      undo,
      redo,
      canUndo,
      canRedo,
      setSearchQuery,
      nextSearchMatch,
      prevSearchMatch,
    }),
    [
      setTree,
      selectNode,
      selectAndDrillDown,
      toggleNodeSelection,
      selectNodeRange,
      setSelection,
      setVisibleNodesOverride,
      drillDown,
      toggleExpand,
      expandNode,
      collapseNode,
      expandAll,
      collapseAll,
      undo,
      redo,
      canUndo,
      canRedo,
      setSearchQuery,
      nextSearchMatch,
      prevSearchMatch,
    ],
  );

  const contextValue = useMemo(() => ({ state, actions }), [state, actions]);

  return (
    <StudioContext.Provider value={contextValue}>
      {children}
    </StudioContext.Provider>
  );
}
