// packages/@visual-json/vue/src/components/FormField.vue
<script setup lang="ts">
import { shallowRef, inject, computed, watch, nextTick } from "vue";
import {
  setValue,
  setKey,
  addProperty,
  removeNode,
  type TreeNode,
} from "@visual-json/core";
import {
  getDisplayKey,
  getResolvedSchema,
  getValueColor as getValueColorFn,
  getDisplayValue as getDisplayValueFn,
  checkRequired as checkRequiredFn,
  parseInputValue,
  setMultiDragImage,
} from "@internal/ui";
import { useStudio } from "../composables/use-studio";
import { FORM_VIEW_KEY } from "./form-view-context";
import EnumInput from "./EnumInput.vue";

// Self-import for recursion
import FormField from "./FormField.vue";

const props = defineProps<{
  node: TreeNode;
  depth: number;
}>();

const ctx = inject(FORM_VIEW_KEY)!;
const { state, actions } = useStudio();

const hovered = shallowRef(false);
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const valueInputRef = shallowRef<any>(null);
const keyInputRef = shallowRef<HTMLInputElement | null>(null);

function focusValueInput() {
  if (valueInputRef.value && typeof valueInputRef.value.focus === "function") {
    valueInputRef.value.focus();
  }
}

const isContainer = computed(
  () => props.node.type === "object" || props.node.type === "array",
);
const isRoot = computed(() => props.node.parentId === null);
const isSelected = computed(() =>
  state.selectedNodeIds.value.has(props.node.id),
);
const isEditing = computed(() => ctx.editingNodeId.value === props.node.id);
const collapsed = computed(() => ctx.collapsedIds.value.has(props.node.id));

const parentIsObject = computed(() => {
  if (!props.node.parentId) return false;
  return state.tree.value.nodesById.get(props.node.parentId)?.type === "object";
});

const propSchema = computed(() =>
  getResolvedSchema(ctx.schema.value, ctx.rootSchema.value, props.node.path),
);

const isRequired = computed(() =>
  checkRequiredFn(props.node, ctx.schema.value, ctx.rootSchema.value),
);
const description = computed(() => propSchema.value?.description);
const isDeprecated = computed(() => propSchema.value?.deprecated);
const fieldTitle = computed(() => propSchema.value?.title);

const isDragTarget = computed(
  () => ctx.dragState.value.dropTargetNodeId === props.node.id,
);
const isDraggedNode = computed(() =>
  ctx.dragState.value.draggedNodeIds.has(props.node.id),
);

function getBorderTopColor() {
  if (isDragTarget.value && ctx.dragState.value.dropPosition === "before") {
    return "var(--vj-accent, #007acc)";
  }
  return "transparent";
}

function getBorderBottomColor() {
  if (isDragTarget.value && ctx.dragState.value.dropPosition === "after") {
    return "var(--vj-accent, #007acc)";
  }
  return "transparent";
}

function getRowBg() {
  if (isSelected.value) {
    return ctx.isFocused.value
      ? "var(--vj-bg-selected, #2a5a1e)"
      : "var(--vj-bg-selected-muted, var(--vj-bg-hover, #2a2d2e))";
  }
  if (hovered.value) return "var(--vj-bg-hover, #2a2d2e)";
  return "transparent";
}

function getRowColor() {
  return isSelected.value && ctx.isFocused.value
    ? "var(--vj-text-selected, var(--vj-text, #cccccc))"
    : "var(--vj-text, #cccccc)";
}

function getValueColor(): string {
  return getValueColorFn(props.node);
}

function getDisplayValue(): string {
  return getDisplayValueFn(props.node);
}

function handleDragOver(e: DragEvent) {
  e.preventDefault();
  const rect = (e.currentTarget as HTMLElement).getBoundingClientRect();
  const midY = rect.top + rect.height / 2;
  ctx.onDragOver(props.node.id, e.clientY < midY ? "before" : "after");
}

function handleDragStart(e: DragEvent) {
  e.dataTransfer!.effectAllowed = "move";
  if (
    state.selectedNodeIds.value.size > 1 &&
    state.selectedNodeIds.value.has(props.node.id)
  ) {
    setMultiDragImage(e.dataTransfer!, state.selectedNodeIds.value.size);
  }
  ctx.onDragStart(props.node.id);
}

function handleValueChange(newValue: string) {
  const parsed = parseInputValue(
    newValue,
    propSchema.value?.type,
    props.node.type,
  );
  const newTree = setValue(state.tree.value, props.node.id, parsed);
  actions.setTree(newTree);
}

function handleKeyChange(newKey: string) {
  const newTree = setKey(state.tree.value, props.node.id, newKey);
  actions.setTree(newTree);
}

function handleRemove() {
  const newTree = removeNode(state.tree.value, props.node.id);
  actions.setTree(newTree);
}

function handleAddChild() {
  const key =
    props.node.type === "array"
      ? String(props.node.children.length)
      : `newKey${props.node.children.length}`;
  const newTree = addProperty(state.tree.value, props.node.id, key, "");
  actions.setTree(newTree);
}

const hasEnumValues = computed(
  () => propSchema.value?.enum && propSchema.value.enum.length > 0,
);

const keyWidth = computed(
  () =>
    `calc(${(ctx.maxDepth.value - props.depth) * 16}px + ${ctx.maxKeyLength.value}ch)`,
);

// Focus the appropriate input when editing starts
watch(isEditing, async (editing) => {
  if (!editing) return;
  await nextTick();
  if (!isContainer.value) {
    const hasValue =
      props.node.value !== null &&
      props.node.value !== undefined &&
      props.node.value !== "";
    if (hasValue && valueInputRef.value) {
      focusValueInput();
    } else if (keyInputRef.value) {
      keyInputRef.value.focus();
    }
  } else if (keyInputRef.value) {
    keyInputRef.value.focus();
  }
});
</script>

<template>
  <!-- Container node (object or array) -->
  <div v-if="isContainer">
    <div
      :data-form-node-id="node.id"
      :draggable="!isRoot"
      :style="{
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        padding: '1px 8px',
        paddingLeft: 8 + depth * 16 + 'px',
        cursor: 'pointer',
        backgroundColor: getRowBg(),
        color: getRowColor(),
        height: '28px',
        boxSizing: 'border-box',
        userSelect: 'none',
        opacity: isDeprecated ? 0.5 : isDraggedNode ? 0.4 : 1,
        borderTop: `2px solid ${getBorderTopColor()}`,
        borderBottom: `2px solid ${getBorderBottomColor()}`,
      }"
      @click.stop="(e) => ctx.onSelect(node.id, e)"
      @dblclick="() => ctx.onToggleCollapse(node.id)"
      @mouseenter="() => (hovered = true)"
      @mouseleave="() => (hovered = false)"
      @dragstart="handleDragStart"
      @dragover="handleDragOver"
      @dragend="() => ctx.onDragEnd()"
      @drop.prevent="() => ctx.onDrop()"
    >
      <button
        :style="{
          background: 'none',
          border: 'none',
          color: 'inherit',
          cursor: 'pointer',
          padding: 0,
          width: '16px',
          fontSize: '9px',
          flexShrink: 0,
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          transition: 'transform 0.15s',
          transform: collapsed ? 'rotate(0deg)' : 'rotate(90deg)',
        }"
        @click.stop="() => ctx.onToggleCollapse(node.id)"
      >
        &#9654;
      </button>

      <input
        v-if="isEditing && !isRoot"
        ref="keyInputRef"
        :value="node.key"
        :style="{
          background: 'none',
          border: 'none',
          color: 'inherit',
          fontFamily: 'var(--vj-font, monospace)',
          fontSize: 'var(--vj-input-font-size, 13px)',
          fontWeight: 500,
          padding: 0,
          outline: 'none',
          flexShrink: 0,
          width: keyWidth,
        }"
        @input="(e) => handleKeyChange((e.target as HTMLInputElement).value)"
        @click.stop
      />
      <span
        v-else
        :style="{
          color:
            !isRoot && !parentIsObject && !isSelected
              ? 'var(--vj-text-muted, #888888)'
              : 'inherit',
          fontSize: 'var(--vj-input-font-size, 13px)',
          fontFamily: 'var(--vj-font, monospace)',
          fontWeight: 500,
          flexShrink: 0,
          display: 'inline-block',
          width: keyWidth,
        }"
      >
        {{ isRoot ? "/" : getDisplayKey(node, state.tree.value) }}
      </span>

      <span
        v-if="ctx.showDescriptions && fieldTitle && !isSelected"
        :style="{
          color: 'var(--vj-text-muted, #888888)',
          fontSize: '11px',
          fontFamily: 'var(--vj-font, monospace)',
        }"
      >
        {{ fieldTitle }}
      </span>

      <button
        v-if="hovered"
        :style="{
          background: 'none',
          border: 'none',
          color: isSelected ? 'inherit' : 'var(--vj-text-muted, #888888)',
          cursor: 'pointer',
          padding: 0,
          fontSize: '12px',
          fontFamily: 'var(--vj-font, monospace)',
        }"
        @click.stop="handleAddChild"
      >
        + Add {{ node.type === "array" ? "item" : "property" }}
      </button>

      <span
        v-if="ctx.showCounts"
        :style="{
          color: isSelected ? 'inherit' : 'var(--vj-text-dim, #666666)',
          fontSize: '12px',
          fontFamily: 'var(--vj-font, monospace)',
          marginLeft: 'auto',
        }"
      >
        {{
          node.type === "array"
            ? `${node.children.length} items`
            : `${node.children.length} properties`
        }}
      </span>

      <button
        v-if="!isRoot && isEditing"
        :style="{
          background: 'none',
          border: 'none',
          color: isSelected ? 'inherit' : 'var(--vj-text-muted, #888888)',
          cursor: 'pointer',
          padding: '2px 4px',
          fontSize: '14px',
          fontFamily: 'var(--vj-font, monospace)',
          ...(!ctx.showCounts ? { marginLeft: 'auto' } : {}),
        }"
        title="Remove"
        @click.stop="handleRemove"
      >
        &times;
      </button>
    </div>

    <div
      v-if="ctx.showDescriptions && description"
      :style="{
        padding: '2px 12px 4px',
        paddingLeft: 8 + depth * 16 + 22 + 'px',
        fontSize: '11px',
        color: 'var(--vj-text-dim, #666666)',
        fontFamily: 'var(--vj-font, monospace)',
      }"
    >
      {{ description }}
    </div>

    <div v-if="!collapsed">
      <FormField
        v-for="child in node.children"
        :key="child.id"
        :node="child"
        :depth="depth + 1"
      />
    </div>
  </div>

  <!-- Leaf node -->
  <div
    v-else
    :data-form-node-id="node.id"
    :draggable="!isRoot"
    :style="{
      display: 'flex',
      alignItems: 'center',
      gap: '6px',
      padding: '1px 8px',
      paddingLeft: 8 + depth * 16 + 'px',
      cursor: 'pointer',
      backgroundColor: getRowBg(),
      color: getRowColor(),
      height: '28px',
      boxSizing: 'border-box',
      userSelect: 'none',
      opacity: isDeprecated ? 0.5 : isDraggedNode ? 0.4 : 1,
      borderTop: `2px solid ${getBorderTopColor()}`,
      borderBottom: `2px solid ${getBorderBottomColor()}`,
    }"
    @click.stop="(e) => ctx.onSelect(node.id, e)"
    @dblclick="() => ctx.onStartEditing(node.id)"
    @mouseenter="() => (hovered = true)"
    @mouseleave="() => (hovered = false)"
    @dragstart="handleDragStart"
    @dragover="handleDragOver"
    @dragend="() => ctx.onDragEnd()"
    @drop.prevent="() => ctx.onDrop()"
  >
    <span :style="{ width: '16px', flexShrink: 0 }" />

    <input
      v-if="isEditing && parentIsObject"
      ref="keyInputRef"
      :value="node.key"
      :style="{
        background: 'none',
        border: 'none',
        color: 'inherit',
        fontFamily: 'var(--vj-font, monospace)',
        fontSize: 'var(--vj-input-font-size, 13px)',
        padding: 0,
        flexShrink: 0,
        outline: 'none',
        width: keyWidth,
      }"
      @input="(e) => handleKeyChange((e.target as HTMLInputElement).value)"
      @click.stop
      @keydown="
        (e: KeyboardEvent) => {
          if (e.key === 'Tab' && !e.shiftKey && valueInputRef) {
            e.preventDefault();
            focusValueInput();
          }
        }
      "
    />
    <span
      v-else
      :style="{
        color:
          !parentIsObject && !isSelected
            ? 'var(--vj-text-muted, #888888)'
            : 'inherit',
        fontSize: 'var(--vj-input-font-size, 13px)',
        fontFamily: 'var(--vj-font, monospace)',
        flexShrink: 0,
        display: 'inline-block',
        width: keyWidth,
      }"
    >
      {{ getDisplayKey(node, state.tree.value) }}
    </span>

    <span
      v-if="isRequired && !isSelected"
      :style="{
        color: 'var(--vj-error, #f48771)',
        fontSize: '10px',
        fontFamily: 'var(--vj-font, monospace)',
      }"
    >
      *
    </span>

    <!-- Editing value -->
    <div
      v-if="isEditing"
      :style="{
        flex: 1,
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        minWidth: 0,
      }"
    >
      <!-- Boolean: EnumInput -->
      <EnumInput
        v-if="node.type === 'boolean'"
        ref="valueInputRef"
        :enum-values="['true', 'false']"
        :value="String(node.value)"
        :input-style="{
          background: 'none',
          border: 'none',
          fontFamily: 'var(--vj-font, monospace)',
          fontSize: 'var(--vj-input-font-size, 13px)',
          padding: '0',
          flex: '1',
          outline: 'none',
          color: getValueColor(),
        }"
        @value-change="handleValueChange"
      />
      <!-- Enum: EnumInput -->
      <EnumInput
        v-else-if="hasEnumValues && propSchema?.enum"
        ref="valueInputRef"
        :enum-values="propSchema.enum"
        :value="getDisplayValue()"
        :input-style="{
          background: 'none',
          border: 'none',
          fontFamily: 'var(--vj-font, monospace)',
          fontSize: 'var(--vj-input-font-size, 13px)',
          padding: '0',
          flex: '1',
          outline: 'none',
          color: getValueColor(),
        }"
        @value-change="handleValueChange"
      />
      <!-- Null: display only -->
      <span
        v-else-if="node.type === 'null'"
        :style="{
          color: 'var(--vj-boolean, #569cd6)',
          fontFamily: 'var(--vj-font, monospace)',
          fontSize: 'var(--vj-input-font-size, 13px)',
          fontStyle: 'italic',
          flex: 1,
        }"
      >
        null
      </span>
      <!-- Text/number input -->
      <input
        v-else
        ref="valueInputRef"
        :value="getDisplayValue()"
        :placeholder="
          propSchema?.default !== undefined
            ? String(propSchema.default)
            : '<value>'
        "
        :style="{
          background: 'none',
          border: 'none',
          fontFamily: 'var(--vj-font, monospace)',
          fontSize: 'var(--vj-input-font-size, 13px)',
          padding: 0,
          flex: 1,
          outline: 'none',
          color: getValueColor(),
        }"
        @input="(e) => handleValueChange((e.target as HTMLInputElement).value)"
        @click.stop
      />
    </div>

    <!-- Display value (not editing) -->
    <span
      v-else
      :style="{
        color: getValueColor(),
        fontSize: 'var(--vj-input-font-size, 13px)',
        fontFamily: 'var(--vj-font, monospace)',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        fontStyle: node.type === 'null' ? 'italic' : undefined,
      }"
    >
      {{ getDisplayValue() }}
    </span>

    <button
      v-if="isEditing"
      :style="{
        background: 'none',
        border: 'none',
        color: isSelected ? 'inherit' : 'var(--vj-text-muted, #888888)',
        cursor: 'pointer',
        padding: '2px 4px',
        fontSize: '14px',
        fontFamily: 'var(--vj-font, monospace)',
        flexShrink: 0,
      }"
      title="Remove"
      @click.stop="handleRemove"
    >
      &times;
    </button>
  </div>
</template>

// packages/@visual-json/svelte/src/components/FormField.svelte
<script lang="ts">
	import { getContext, tick } from 'svelte';
	import { setValue, setKey, addProperty, removeNode, type TreeNode } from '@visual-json/core';
	import {
		getDisplayKey,
		getResolvedSchema,
		getValueColor as getValueColorFn,
		getDisplayValue as getDisplayValueFn,
		checkRequired as checkRequiredFn,
		parseInputValue,
		setMultiDragImage
	} from '@internal/ui';
	import { useStudio } from '../use-studio.js';
	import { FORM_VIEW_KEY, type FormViewContext } from '../form-view-context.js';
	import EnumInput from './EnumInput.svelte';
	import FormField from './FormField.svelte';

	interface Props {
		node: TreeNode;
		depth: number;
	}

	let { node, depth }: Props = $props();

	const ctx = getContext<FormViewContext>(FORM_VIEW_KEY);
	const { state: studioState, actions } = useStudio();

	let hovered = $state(false);
	let valueInputRef = $state<EnumInput | HTMLInputElement | null>(null);
	let keyInputRef = $state<HTMLInputElement | null>(null);

	function focusValueInput() {
		if (valueInputRef && 'focus' in valueInputRef && typeof valueInputRef.focus === 'function') {
			valueInputRef.focus();
		}
	}

	const isContainer = $derived(node.type === 'object' || node.type === 'array');
	const isRoot = $derived(node.parentId === null);
	const isSelected = $derived(studioState.selectedNodeIds.has(node.id));
	const isEditing = $derived(ctx.editingNodeId === node.id);
	const collapsed = $derived(ctx.collapsedIds.has(node.id));

	const parentIsObject = $derived(
		node.parentId ? studioState.tree.nodesById.get(node.parentId)?.type === 'object' : false
	);

	const propSchema = $derived(getResolvedSchema(ctx.schema, ctx.rootSchema, node.path));
	const isRequired = $derived(checkRequiredFn(node, ctx.schema, ctx.rootSchema));
	const description = $derived(propSchema?.description);
	const isDeprecated = $derived(propSchema?.deprecated);
	const fieldTitle = $derived(propSchema?.title);

	const isDragTarget = $derived(ctx.dragState.dropTargetNodeId === node.id);
	const isDraggedNode = $derived(ctx.dragState.draggedNodeIds.has(node.id));

	const hasEnumValues = $derived(
		propSchema?.enum !== undefined && (propSchema.enum as unknown[]).length > 0
	);

	const keyWidth = $derived(
		`calc(${(ctx.maxDepth - depth) * 16}px + ${ctx.maxKeyLength}ch)`
	);

	function getBorderTopColor() {
		if (isDragTarget && ctx.dragState.dropPosition === 'before') return 'var(--vj-accent, #007acc)';
		return 'transparent';
	}

	function getBorderBottomColor() {
		if (isDragTarget && ctx.dragState.dropPosition === 'after') return 'var(--vj-accent, #007acc)';
		return 'transparent';
	}

	function getRowBg() {
		if (isSelected) {
			return ctx.isFocused
				? 'var(--vj-bg-selected, #2a5a1e)'
				: 'var(--vj-bg-selected-muted, var(--vj-bg-hover, #2a2d2e))';
		}
		if (hovered) return 'var(--vj-bg-hover, #2a2d2e)';
		return 'transparent';
	}

	function getRowColor() {
		return isSelected && ctx.isFocused
			? 'var(--vj-text-selected, var(--vj-text, #cccccc))'
			: 'var(--vj-text, #cccccc)';
	}

	function getValueColor(): string {
		return getValueColorFn(node);
	}

	function getDisplayValue(): string {
		return getDisplayValueFn(node);
	}

	function handleDragOver(e: DragEvent) {
		e.preventDefault();
		const rect = (e.currentTarget as HTMLElement).getBoundingClientRect();
		const midY = rect.top + rect.height / 2;
		ctx.onDragOver(node.id, e.clientY < midY ? 'before' : 'after');
	}

	function handleDragStart(e: DragEvent) {
		e.dataTransfer!.effectAllowed = 'move';
		if (studioState.selectedNodeIds.size > 1 && studioState.selectedNodeIds.has(node.id)) {
			setMultiDragImage(e.dataTransfer!, studioState.selectedNodeIds.size);
		}
		ctx.onDragStart(node.id);
	}

	function handleValueChange(newValue: string) {
		const parsed = parseInputValue(newValue, propSchema?.type, node.type);
		const newTree = setValue(studioState.tree, node.id, parsed);
		actions.setTree(newTree);
	}

	function handleKeyChange(newKey: string) {
		const newTree = setKey(studioState.tree, node.id, newKey);
		actions.setTree(newTree);
	}

	function handleRemove() {
		const newTree = removeNode(studioState.tree, node.id);
		actions.setTree(newTree);
	}

	function handleAddChild() {
		const key =
			node.type === 'array' ? String(node.children.length) : `newKey${node.children.length}`;
		const newTree = addProperty(studioState.tree, node.id, key, '');
		actions.setTree(newTree);
	}

	// Focus appropriate input when editing starts
	$effect(() => {
		if (!isEditing) return;
		tick().then(() => {
			if (!isContainer) {
				const hasValue =
					node.value !== null && node.value !== undefined && node.value !== '';
				if (hasValue && valueInputRef) {
					focusValueInput();
				} else if (keyInputRef) {
					keyInputRef.focus();
				}
			} else if (keyInputRef) {
				keyInputRef.focus();
			}
		});
	});
</script>

{#if isContainer}
	<div>
		<div
			role="treeitem"
			aria-selected={isSelected}
			aria-expanded={!collapsed}
			tabindex="-1"
			data-form-node-id={node.id}
			draggable={!isRoot}
			style="
				display: flex;
				align-items: center;
				gap: 6px;
				padding: 1px 8px;
				padding-left: {8 + depth * 16}px;
				cursor: pointer;
				background-color: {getRowBg()};
				color: {getRowColor()};
				height: 28px;
				box-sizing: border-box;
				user-select: none;
				opacity: {isDeprecated ? 0.5 : isDraggedNode ? 0.4 : 1};
				border-top: 2px solid {getBorderTopColor()};
				border-bottom: 2px solid {getBorderBottomColor()};
			"
			onclick={(e) => { e.stopPropagation(); ctx.onSelect(node.id, e); }}
			onkeydown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); ctx.onToggleCollapse(node.id); } }}
			ondblclick={() => ctx.onToggleCollapse(node.id)}
			onmouseenter={() => (hovered = true)}
			onmouseleave={() => (hovered = false)}
			ondragstart={handleDragStart}
			ondragover={handleDragOver}
			ondragend={() => ctx.onDragEnd()}
			ondrop={(e) => { e.preventDefault(); ctx.onDrop(); }}
		>
			<button
				style="
					background: none;
					border: none;
					color: inherit;
					cursor: pointer;
					padding: 0;
					width: 16px;
					font-size: 9px;
					flex-shrink: 0;
					display: inline-flex;
					align-items: center;
					justify-content: center;
					transition: transform 0.15s;
					transform: {collapsed ? 'rotate(0deg)' : 'rotate(90deg)'};
				"
				onclick={(e) => { e.stopPropagation(); ctx.onToggleCollapse(node.id); }}
			>
				&#9654;
			</button>

			{#if isEditing && !isRoot}
				<input
					bind:this={keyInputRef}
					value={node.key}
					style="
						background: none;
						border: none;
						color: inherit;
						font-family: var(--vj-font, monospace);
						font-size: var(--vj-input-font-size, 13px);
						font-weight: 500;
						padding: 0;
						outline: none;
						flex-shrink: 0;
						width: {keyWidth};
					"
					oninput={(e) => handleKeyChange((e.target as HTMLInputElement).value)}
					onclick={(e) => e.stopPropagation()}
				/>
			{:else}
				<span
					style="
						color: {!isRoot && !parentIsObject && !isSelected ? 'var(--vj-text-muted, #888888)' : 'inherit'};
						font-size: var(--vj-input-font-size, 13px);
						font-family: var(--vj-font, monospace);
						font-weight: 500;
						flex-shrink: 0;
						display: inline-block;
						width: {keyWidth};
					"
				>
					{isRoot ? '/' : getDisplayKey(node, studioState.tree)}
				</span>
			{/if}

			{#if ctx.showDescriptions && fieldTitle && !isSelected}
				<span
					style="color: var(--vj-text-muted, #888888); font-size: 11px; font-family: var(--vj-font, monospace);"
				>
					{fieldTitle}
				</span>
			{/if}

			{#if hovered}
				<button
					style="
						background: none;
						border: none;
						color: {isSelected ? 'inherit' : 'var(--vj-text-muted, #888888)'};
						cursor: pointer;
						padding: 0;
						font-size: 12px;
						font-family: var(--vj-font, monospace);
					"
					onclick={(e) => { e.stopPropagation(); handleAddChild(); }}
				>
					+ Add {node.type === 'array' ? 'item' : 'property'}
				</button>
			{/if}

			{#if ctx.showCounts}
				<span
					style="
						color: {isSelected ? 'inherit' : 'var(--vj-text-dim, #666666)'};
						font-size: 12px;
						font-family: var(--vj-font, monospace);
						margin-left: auto;
					"
				>
					{node.type === 'array'
						? `${node.children.length} items`
						: `${node.children.length} properties`}
				</span>
			{/if}

			{#if !isRoot && isEditing}
				<button
					style="
						background: none;
						border: none;
						color: {isSelected ? 'inherit' : 'var(--vj-text-muted, #888888)'};
						cursor: pointer;
						padding: 2px 4px;
						font-size: 14px;
						font-family: var(--vj-font, monospace);
						{!ctx.showCounts ? 'margin-left: auto;' : ''}
					"
					title="Remove"
					onclick={(e) => { e.stopPropagation(); handleRemove(); }}
				>
					&times;
				</button>
			{/if}
		</div>

		{#if ctx.showDescriptions && description}
			<div
				style="
					padding: 2px 12px 4px;
					padding-left: {8 + depth * 16 + 22}px;
					font-size: 11px;
					color: var(--vj-text-dim, #666666);
					font-family: var(--vj-font, monospace);
				"
			>
				{description}
			</div>
		{/if}

		{#if !collapsed}
			{#each node.children as child (child.id)}
				<FormField node={child} depth={depth + 1} />
			{/each}
		{/if}
	</div>
{:else}
	<!-- Leaf node -->
	<div
		role="treeitem"
		aria-selected={isSelected}
		tabindex="-1"
		data-form-node-id={node.id}
		draggable={!isRoot}
		style="
			display: flex;
			align-items: center;
			gap: 6px;
			padding: 1px 8px;
			padding-left: {8 + depth * 16}px;
			cursor: pointer;
			background-color: {getRowBg()};
			color: {getRowColor()};
			height: 28px;
			box-sizing: border-box;
			user-select: none;
			opacity: {isDeprecated ? 0.5 : isDraggedNode ? 0.4 : 1};
			border-top: 2px solid {getBorderTopColor()};
			border-bottom: 2px solid {getBorderBottomColor()};
		"
		onclick={(e) => { e.stopPropagation(); ctx.onSelect(node.id, e); }}
		onkeydown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); ctx.onStartEditing(node.id); } }}
		ondblclick={() => ctx.onStartEditing(node.id)}
		onmouseenter={() => (hovered = true)}
		onmouseleave={() => (hovered = false)}
		ondragstart={handleDragStart}
		ondragover={handleDragOver}
		ondragend={() => ctx.onDragEnd()}
		ondrop={(e) => { e.preventDefault(); ctx.onDrop(); }}
	>
		<span style="width: 16px; flex-shrink: 0;"></span>

		{#if isEditing && parentIsObject}
			<input
				bind:this={keyInputRef}
				value={node.key}
				style="
					background: none;
					border: none;
					color: inherit;
					font-family: var(--vj-font, monospace);
					font-size: var(--vj-input-font-size, 13px);
					padding: 0;
					flex-shrink: 0;
					outline: none;
					width: {keyWidth};
				"
				oninput={(e) => handleKeyChange((e.target as HTMLInputElement).value)}
				onclick={(e) => e.stopPropagation()}
				onkeydown={(e) => {
					if (e.key === 'Tab' && !e.shiftKey && valueInputRef) {
						e.preventDefault();
						focusValueInput();
					}
				}}
			/>
		{:else}
			<span
				style="
					color: {!parentIsObject && !isSelected ? 'var(--vj-text-muted, #888888)' : 'inherit'};
					font-size: var(--vj-input-font-size, 13px);
					font-family: var(--vj-font, monospace);
					flex-shrink: 0;
					display: inline-block;
					width: {keyWidth};
				"
			>
				{getDisplayKey(node, studioState.tree)}
			</span>
		{/if}

		{#if isRequired && !isSelected}
			<span style="color: var(--vj-error, #f48771); font-size: 10px; font-family: var(--vj-font, monospace);">
				*
			</span>
		{/if}

		{#if isEditing}
			<div style="flex: 1; display: flex; align-items: center; gap: 6px; min-width: 0;">
				{#if node.type === 'boolean'}
					<EnumInput
						bind:this={valueInputRef}
						enumValues={['true', 'false']}
						value={String(node.value)}
						inputStyle={{
							background: 'none',
							border: 'none',
							fontFamily: 'var(--vj-font, monospace)',
							fontSize: 'var(--vj-input-font-size, 13px)',
							padding: '0',
							flex: '1',
							outline: 'none',
							color: getValueColor()
						}}
						onvaluechange={handleValueChange}
					/>
				{:else if hasEnumValues && propSchema?.enum}
					<EnumInput
						bind:this={valueInputRef}
						enumValues={propSchema.enum as import('@visual-json/core').JsonValue[]}
						value={getDisplayValue()}
						inputStyle={{
							background: 'none',
							border: 'none',
							fontFamily: 'var(--vj-font, monospace)',
							fontSize: 'var(--vj-input-font-size, 13px)',
							padding: '0',
							flex: '1',
							outline: 'none',
							color: getValueColor()
						}}
						onvaluechange={handleValueChange}
					/>
				{:else if node.type === 'null'}
					<span
						style="
							color: var(--vj-boolean, #569cd6);
							font-family: var(--vj-font, monospace);
							font-size: var(--vj-input-font-size, 13px);
							font-style: italic;
							flex: 1;
						"
					>
						null
					</span>
				{:else}
					<input
						bind:this={valueInputRef}
						value={getDisplayValue()}
						placeholder={propSchema?.default !== undefined
							? String(propSchema.default)
							: '<value>'}
						style="
							background: none;
							border: none;
							font-family: var(--vj-font, monospace);
							font-size: var(--vj-input-font-size, 13px);
							padding: 0;
							flex: 1;
							outline: none;
							color: {getValueColor()};
						"
						oninput={(e) => handleValueChange((e.target as HTMLInputElement).value)}
						onclick={(e) => e.stopPropagation()}
					/>
				{/if}
			</div>
		{:else}
			<span
				style="
					color: {getValueColor()};
					font-size: var(--vj-input-font-size, 13px);
					font-family: var(--vj-font, monospace);
					overflow: hidden;
					text-overflow: ellipsis;
					white-space: nowrap;
					{node.type === 'null' ? 'font-style: italic;' : ''}
				"
			>
				{getDisplayValue()}
			</span>
		{/if}

		{#if isEditing}
			<button
				style="
					background: none;
					border: none;
					color: {isSelected ? 'inherit' : 'var(--vj-text-muted, #888888)'};
					cursor: pointer;
					padding: 2px 4px;
					font-size: 14px;
					font-family: var(--vj-font, monospace);
					flex-shrink: 0;
				"
				title="Remove"
				onclick={(e) => { e.stopPropagation(); handleRemove(); }}
			>
				&times;
			</button>
		{/if}
	</div>
{/if}
