// packages/vue/src/components/VisualJson.vue
<script setup lang="ts">
import { shallowRef, computed, watch, onMounted, onUnmounted, provide } from "vue";
import {
  fromJson,
  toJson,
  History,
  searchNodes,
  getAncestorIds,
  type JsonValue,
  type JsonSchema,
  type TreeState,
  type TreeNode,
  type SearchMatch,
} from "@visual-json/core";
import { collectAllIds, getVisibleNodes } from "@visual-json/ui-shared";
import { STUDIO_KEY } from "../provide-inject";
import type { StudioState, StudioActions } from "../provide-inject";
import { computeRangeIds } from "../selection-utils";

const props = withDefaults(
  defineProps<{
    value: JsonValue;
    schema?: JsonSchema | null;
  }>(),
  { schema: null },
);

const emit = defineEmits<{
  change: [value: JsonValue];
}>();

const tree = shallowRef<TreeState>(fromJson(props.value));
const focusedNodeId = shallowRef<string | null>(null);
const selectedNodeIds = shallowRef<Set<string>>(new Set<string>());
const anchorNodeId = shallowRef<string | null>(null);
const drillDownNodeId = shallowRef<string | null>(null);
const expandedNodeIds = shallowRef<Set<string>>(new Set([tree.value.root.id]));

const visibleNodes = computed(() =>
  getVisibleNodes(tree.value.root, (id) => expandedNodeIds.value.has(id)),
);

let visibleNodesOverride: TreeNode[] | null = null;

let history = new History();
const historyVersion = shallowRef(0);
const canUndo = computed(() => {
  historyVersion.value;
  return history.canUndo;
});
const canRedo = computed(() => {
  historyVersion.value;
  return history.canRedo;
});

const searchQuery = shallowRef("");
const searchMatches = shallowRef<SearchMatch[]>([]);
const searchMatchIndex = shallowRef(0);
const searchMatchNodeIds = computed(
  () => new Set(searchMatches.value.map((m) => m.nodeId)),
);

let isInternalChange = false;

// Initialize history with initial state
history.push(tree.value);

function focusSelectAndDrillDown(nodeId: string | null) {
  focusedNodeId.value = nodeId;
  selectedNodeIds.value = nodeId ? new Set([nodeId]) : new Set<string>();
  anchorNodeId.value = nodeId;
  drillDownNodeId.value = nodeId;
}

// Sync external value changes
watch(
  () => props.value,
  (val) => {
    if (isInternalChange) {
      isInternalChange = false;
      return;
    }
    const newTree = fromJson(val);
    tree.value = newTree;
    expandedNodeIds.value = new Set([newTree.root.id]);
    focusSelectAndDrillDown(null);
    history = new History();
    history.push(newTree);
    historyVersion.value++;
    searchQuery.value = "";
    searchMatches.value = [];
    searchMatchIndex.value = 0;
  },
  { flush: "sync" },
);

// Update search results when tree changes
watch(
  tree,
  (newTree) => {
    if (!searchQuery.value.trim()) return;
    const matches = searchNodes(newTree, searchQuery.value);
    searchMatches.value = matches;
    searchMatchIndex.value = Math.min(
      searchMatchIndex.value,
      Math.max(matches.length - 1, 0),
    );
  },
  { flush: "sync" },
);

function setTree(newTree: TreeState) {
  tree.value = newTree;
  history.push(newTree);
  historyVersion.value++;
  isInternalChange = true;
  emit("change", toJson(newTree.root));
}

function undo() {
  const prev = history.undo();
  if (prev) {
    tree.value = prev;
    historyVersion.value++;
    isInternalChange = true;
    emit("change", toJson(prev.root));
  }
}

function redo() {
  const next = history.redo();
  if (next) {
    tree.value = next;
    historyVersion.value++;
    isInternalChange = true;
    emit("change", toJson(next.root));
  }
}

function handleKeyDown(e: KeyboardEvent) {
  const mod = e.metaKey || e.ctrlKey;
  if (mod && e.key === "z" && !e.shiftKey) {
    e.preventDefault();
    undo();
  } else if (mod && e.key === "z" && e.shiftKey) {
    e.preventDefault();
    redo();
  } else if (mod && e.key === "y") {
    e.preventDefault();
    redo();
  }
}

onMounted(() => document.addEventListener("keydown", handleKeyDown));
onUnmounted(() => document.removeEventListener("keydown", handleKeyDown));

const state: StudioState = {
  tree,
  focusedNodeId,
  selectedNodeIds,
  anchorNodeId,
  drillDownNodeId,
  expandedNodeIds,
  schema: computed<JsonSchema | null>(() => props.schema ?? null),
  searchQuery,
  searchMatches,
  searchMatchIndex,
  searchMatchNodeIds,
  canUndo,
  canRedo,
};

const actions: StudioActions = {
  setTree,
  selectNode(nodeId) {
    focusedNodeId.value = nodeId;
    selectedNodeIds.value = nodeId ? new Set([nodeId]) : new Set<string>();
    anchorNodeId.value = nodeId;
  },
  selectAndDrillDown: focusSelectAndDrillDown,
  toggleNodeSelection(nodeId) {
    const next = new Set(selectedNodeIds.value);
    if (next.has(nodeId)) {
      next.delete(nodeId);
    } else {
      next.add(nodeId);
    }
    selectedNodeIds.value = next;
    if (next.size === 0) {
      focusedNodeId.value = null;
      anchorNodeId.value = null;
    } else {
      focusedNodeId.value = nodeId;
      anchorNodeId.value = nodeId;
    }
  },
  selectNodeRange(toNodeId) {
    const nodes = visibleNodesOverride ?? visibleNodes.value;
    const anchor = anchorNodeId.value;
    if (!anchor) {
      focusedNodeId.value = toNodeId;
      selectedNodeIds.value = new Set([toNodeId]);
      anchorNodeId.value = toNodeId;
      return;
    }
    const rangeIds = computeRangeIds(nodes, anchor, toNodeId);
    if (!rangeIds) {
      focusedNodeId.value = toNodeId;
      selectedNodeIds.value = new Set([toNodeId]);
      anchorNodeId.value = toNodeId;
      return;
    }
    selectedNodeIds.value = rangeIds;
    focusedNodeId.value = toNodeId;
  },
  setSelection(focusedId, newSelectedIds, newAnchorId) {
    focusedNodeId.value = focusedId;
    selectedNodeIds.value = newSelectedIds;
    anchorNodeId.value = newAnchorId;
  },
  setVisibleNodesOverride(nodes) {
    visibleNodesOverride = nodes;
  },
  drillDown(nodeId) {
    drillDownNodeId.value = nodeId;
  },
  toggleExpand(nodeId) {
    const next = new Set(expandedNodeIds.value);
    if (next.has(nodeId)) next.delete(nodeId);
    else next.add(nodeId);
    expandedNodeIds.value = next;
  },
  expandNode(nodeId) {
    const next = new Set(expandedNodeIds.value);
    next.add(nodeId);
    expandedNodeIds.value = next;
  },
  collapseNode(nodeId) {
    const next = new Set(expandedNodeIds.value);
    next.delete(nodeId);
    expandedNodeIds.value = next;
  },
  expandAll() {
    expandedNodeIds.value = new Set(collectAllIds(tree.value.root));
  },
  collapseAll() {
    expandedNodeIds.value = new Set([tree.value.root.id]);
  },
  undo,
  redo,
  setSearchQuery(query) {
    searchQuery.value = query;
    if (!query.trim()) {
      searchMatches.value = [];
      searchMatchIndex.value = 0;
      return;
    }
    const matches = searchNodes(tree.value, query);
    searchMatches.value = matches;
    searchMatchIndex.value = 0;

    if (matches.length > 0) {
      const ancestors = getAncestorIds(
        tree.value,
        matches.map((m) => m.nodeId),
      );
      const next = new Set(expandedNodeIds.value);
      for (const id of ancestors) next.add(id);
      expandedNodeIds.value = next;
      focusSelectAndDrillDown(matches[0].nodeId);
    }
  },
  nextSearchMatch() {
    if (searchMatches.value.length === 0) return;
    const nextIdx = (searchMatchIndex.value + 1) % searchMatches.value.length;
    searchMatchIndex.value = nextIdx;
    focusSelectAndDrillDown(searchMatches.value[nextIdx].nodeId);
  },
  prevSearchMatch() {
    if (searchMatches.value.length === 0) return;
    const prevIdx =
      (searchMatchIndex.value - 1 + searchMatches.value.length) %
      searchMatches.value.length;
    searchMatchIndex.value = prevIdx;
    focusSelectAndDrillDown(searchMatches.value[prevIdx].nodeId);
  },
};

provide(STUDIO_KEY, { state, actions });
</script>

<template>
  <slot />
</template>

// packages/@visual-json/svelte/src/components/VisualJson.svelte
<script lang="ts">
	import { setContext } from 'svelte';
	import type { Snippet } from 'svelte';
	import {
		fromJson,
		toJson,
		History,
		searchNodes,
		getAncestorIds,
		type JsonValue,
		type JsonSchema,
		type TreeState,
		type TreeNode,
		type SearchMatch
	} from '@visual-json/core';
	import { collectAllIds, getVisibleNodes } from '@internal/ui';
	import { STUDIO_KEY, type StudioState, type StudioActions } from '../context.js';
	import { computeRangeIds } from '../selection-utils.js';

	interface Props {
		value: JsonValue;
		schema?: JsonSchema | null;
		onchange?: (value: JsonValue) => void;
		children?: Snippet;
	}

	let { value, schema = null, onchange, children }: Props = $props();

	let tree = $state<TreeState>(fromJson(value));
	let focusedNodeId = $state<string | null>(null);
	let selectedNodeIds = $state<Set<string>>(new Set());
	let anchorNodeId = $state<string | null>(null);
	let drillDownNodeId = $state<string | null>(null);
	let expandedNodeIds = $state<Set<string>>(new Set([tree.root.id]));

	let visibleNodesOverride: TreeNode[] | null = null;
	let history = new History();
	let historyVersion = $state(0);

	let searchQuery = $state('');
	let searchMatches = $state<SearchMatch[]>([]);
	let searchMatchIndex = $state(0);

	let isInternalChange = false;

	history.push(tree);

	function focusSelectAndDrillDown(nodeId: string | null) {
		focusedNodeId = nodeId;
		selectedNodeIds = nodeId ? new Set([nodeId]) : new Set();
		anchorNodeId = nodeId;
		drillDownNodeId = nodeId;
	}

	// Sync external value changes
	$effect(() => {
		const v = value;
		if (isInternalChange) {
			isInternalChange = false;
			return;
		}
		const newTree = fromJson(v);
		tree = newTree;
		expandedNodeIds = new Set([newTree.root.id]);
		focusSelectAndDrillDown(null);
		history = new History();
		history.push(newTree);
		historyVersion++;
		searchQuery = '';
		searchMatches = [];
		searchMatchIndex = 0;
	});

	// Update search results when tree changes
	$effect(() => {
		const currentTree = tree;
		const query = searchQuery;
		if (!query.trim()) return;
		const matches = searchNodes(currentTree, query);
		searchMatches = matches;
		searchMatchIndex = Math.min(searchMatchIndex, Math.max(matches.length - 1, 0));
	});

	function setTree(newTree: TreeState) {
		tree = newTree;
		history.push(newTree);
		historyVersion++;
		isInternalChange = true;
		onchange?.(toJson(newTree.root));
	}

	function undo() {
		const prev = history.undo();
		if (prev) {
			tree = prev;
			historyVersion++;
			isInternalChange = true;
			onchange?.(toJson(prev.root));
		}
	}

	function redo() {
		const next = history.redo();
		if (next) {
			tree = next;
			historyVersion++;
			isInternalChange = true;
			onchange?.(toJson(next.root));
		}
	}

	function handleKeyDown(e: KeyboardEvent) {
		const mod = e.metaKey || e.ctrlKey;
		if (mod && e.key === 'z' && !e.shiftKey) {
			e.preventDefault();
			undo();
		} else if (mod && e.key === 'z' && e.shiftKey) {
			e.preventDefault();
			redo();
		} else if (mod && e.key === 'y') {
			e.preventDefault();
			redo();
		}
	}

	$effect(() => {
		document.addEventListener('keydown', handleKeyDown);
		return () => document.removeEventListener('keydown', handleKeyDown);
	});

	const visibleNodes = $derived(getVisibleNodes(tree.root, (id) => expandedNodeIds.has(id)));

	const stateCtx: StudioState = {
		get tree() {
			return tree;
		},
		get focusedNodeId() {
			return focusedNodeId;
		},
		get selectedNodeIds() {
			return selectedNodeIds;
		},
		get anchorNodeId() {
			return anchorNodeId;
		},
		get drillDownNodeId() {
			return drillDownNodeId;
		},
		get expandedNodeIds() {
			return expandedNodeIds;
		},
		get schema() {
			return schema ?? null;
		},
		get searchQuery() {
			return searchQuery;
		},
		get searchMatches() {
			return searchMatches;
		},
		get searchMatchIndex() {
			return searchMatchIndex;
		},
		get searchMatchNodeIds() {
			return new Set(searchMatches.map((m) => m.nodeId));
		},
		get canUndo() {
			return historyVersion >= 0 && history.canUndo;
		},
		get canRedo() {
			return historyVersion >= 0 && history.canRedo;
		}
	};

	const actions: StudioActions = {
		setTree,
		selectNode(nodeId) {
			focusedNodeId = nodeId;
			selectedNodeIds = nodeId ? new Set([nodeId]) : new Set();
			anchorNodeId = nodeId;
		},
		selectAndDrillDown: focusSelectAndDrillDown,
		toggleNodeSelection(nodeId) {
			const next = new Set(selectedNodeIds);
			if (next.has(nodeId)) {
				next.delete(nodeId);
			} else {
				next.add(nodeId);
			}
			selectedNodeIds = next;
			if (next.size === 0) {
				focusedNodeId = null;
				anchorNodeId = null;
			} else {
				focusedNodeId = nodeId;
				anchorNodeId = nodeId;
			}
		},
		selectNodeRange(toNodeId) {
			const nodes = visibleNodesOverride ?? visibleNodes;
			const anchor = anchorNodeId;
			if (!anchor) {
				focusedNodeId = toNodeId;
				selectedNodeIds = new Set([toNodeId]);
				anchorNodeId = toNodeId;
				return;
			}
			const rangeIds = computeRangeIds(nodes, anchor, toNodeId);
			if (!rangeIds) {
				focusedNodeId = toNodeId;
				selectedNodeIds = new Set([toNodeId]);
				anchorNodeId = toNodeId;
				return;
			}
			selectedNodeIds = rangeIds;
			focusedNodeId = toNodeId;
		},
		setSelection(focusedId, newSelectedIds, newAnchorId) {
			focusedNodeId = focusedId;
			selectedNodeIds = newSelectedIds;
			anchorNodeId = newAnchorId;
		},
		setVisibleNodesOverride(nodes) {
			visibleNodesOverride = nodes;
		},
		drillDown(nodeId) {
			drillDownNodeId = nodeId;
		},
		toggleExpand(nodeId) {
			const next = new Set(expandedNodeIds);
			if (next.has(nodeId)) next.delete(nodeId);
			else next.add(nodeId);
			expandedNodeIds = next;
		},
		expandNode(nodeId) {
			expandedNodeIds = new Set([...expandedNodeIds, nodeId]);
		},
		collapseNode(nodeId) {
			const next = new Set(expandedNodeIds);
			next.delete(nodeId);
			expandedNodeIds = next;
		},
		expandAll() {
			expandedNodeIds = new Set(collectAllIds(tree.root));
		},
		collapseAll() {
			expandedNodeIds = new Set([tree.root.id]);
		},
		undo,
		redo,
		setSearchQuery(query) {
			searchQuery = query;
			if (!query.trim()) {
				searchMatches = [];
				searchMatchIndex = 0;
				return;
			}
			const matches = searchNodes(tree, query);
			searchMatches = matches;
			searchMatchIndex = 0;
			if (matches.length > 0) {
				const ancestors = getAncestorIds(
					tree,
					matches.map((m) => m.nodeId)
				);
				const next = new Set(expandedNodeIds);
				for (const id of ancestors) next.add(id);
				expandedNodeIds = next;
				focusSelectAndDrillDown(matches[0].nodeId);
			}
		},
		nextSearchMatch() {
			if (searchMatches.length === 0) return;
			const nextIdx = (searchMatchIndex + 1) % searchMatches.length;
			searchMatchIndex = nextIdx;
			focusSelectAndDrillDown(searchMatches[nextIdx].nodeId);
		},
		prevSearchMatch() {
			if (searchMatches.length === 0) return;
			const prevIdx = (searchMatchIndex - 1 + searchMatches.length) % searchMatches.length;
			searchMatchIndex = prevIdx;
			focusSelectAndDrillDown(searchMatches[prevIdx].nodeId);
		}
	};

	setContext(STUDIO_KEY, { state: stateCtx, actions });
</script>

{@render children?.()}
