// packages/@visual-json/vue/src/components/JsonEditor.vue
<script setup lang="ts">
import {
  shallowRef,
  computed,
  watch,
  onMounted,
  onUnmounted,
  type CSSProperties,
} from "vue";
import type { JsonValue, JsonSchema } from "@visual-json/core";
import { DEFAULT_CSS_VARS } from "@internal/ui";
import VisualJson from "./VisualJson.vue";
import TreeView from "./TreeView.vue";
import FormView from "./FormView.vue";
import SearchBar from "./SearchBar.vue";

const props = withDefaults(
  defineProps<{
    value?: JsonValue;
    defaultValue?: JsonValue;
    onChange?: (value: JsonValue) => void;
    schema?: JsonSchema | null;
    height?: string | number;
    width?: string | number;
    class?: string;
    style?: Record<string, string>;
    readOnly?: boolean;
    treeShowValues?: boolean;
    treeShowCounts?: boolean;
    editorShowDescriptions?: boolean;
    editorShowCounts?: boolean;
    sidebarOpen?: boolean;
  }>(),
  {
    schema: null,
    height: "100%",
    width: "100%",
    readOnly: false,
    treeShowValues: true,
    treeShowCounts: false,
    editorShowDescriptions: false,
    editorShowCounts: false,
    sidebarOpen: true,
  },
);

const emit = defineEmits<{
  change: [value: JsonValue];
}>();

const isControlled = props.value !== undefined;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const currentValue = shallowRef<any>(
  isControlled ? props.value : (props.defaultValue ?? {}),
);
const editorKey = shallowRef(0);

watch(
  () => props.value,
  (val) => {
    if (isControlled && val !== currentValue.value) {
      currentValue.value = val as JsonValue;
      editorKey.value++;
    }
  },
);

function handleChange(newValue: JsonValue) {
  currentValue.value = newValue;
  if (!props.readOnly) {
    emit("change", newValue);
    props.onChange?.(newValue);
  }
}

// Layout state
const sidebarWidth = shallowRef(280);
const isNarrow = shallowRef(false);
const activePanel = shallowRef<"tree" | "form">("tree");
const containerRef = shallowRef<HTMLDivElement | null>(null);
let dragging = false;
let startX = 0;
let startWidth = 0;
let observer: ResizeObserver | null = null;

function checkWidth() {
  if (containerRef.value) {
    isNarrow.value = containerRef.value.offsetWidth < 500;
  }
}

onMounted(() => {
  checkWidth();
  if (containerRef.value) {
    observer = new ResizeObserver(checkWidth);
    observer.observe(containerRef.value);
  }
});

onUnmounted(() => {
  observer?.disconnect();
});

function handleMouseDown(e: MouseEvent) {
  dragging = true;
  startX = e.clientX;
  startWidth = sidebarWidth.value;
  document.body.style.cursor = "col-resize";
  document.body.style.userSelect = "none";

  function handleMouseMove(ev: MouseEvent) {
    if (!dragging) return;
    const delta = ev.clientX - startX;
    sidebarWidth.value = Math.max(180, Math.min(600, startWidth + delta));
  }

  function handleMouseUp() {
    dragging = false;
    document.body.style.cursor = "";
    document.body.style.userSelect = "";
    document.removeEventListener("mousemove", handleMouseMove);
    document.removeEventListener("mouseup", handleMouseUp);
  }

  document.addEventListener("mousemove", handleMouseMove);
  document.addEventListener("mouseup", handleMouseUp);
}

const containerStyle = computed<CSSProperties>(() => ({
  height: typeof props.height === "number" ? `${props.height}px` : props.height,
  width: typeof props.width === "number" ? `${props.width}px` : props.width,
  display: "flex",
  flexDirection: "column",
  overflow: "hidden",
  ...DEFAULT_CSS_VARS,
  ...(props.style ?? {}),
}));
</script>

<template>
  <div data-vj-root="" :style="containerStyle">
    <style>
      @media (pointer: coarse) {
        [data-vj-root] {
          --vj-input-font-size: 16px;
        }
      }
    </style>
    <VisualJson
      :key="editorKey"
      :value="currentValue"
      :schema="props.schema"
      @change="handleChange"
    >
      <!-- Narrow layout (< 500px) -->
      <div
        v-if="isNarrow"
        ref="containerRef"
        :style="{
          display: 'flex',
          flexDirection: 'column',
          flex: 1,
          minHeight: 0,
        }"
      >
        <!-- No sidebar mode: form only -->
        <template v-if="!props.sidebarOpen">
          <div :style="{ flex: 1, minHeight: 0 }">
            <FormView
              :show-descriptions="props.editorShowDescriptions"
              :show-counts="props.editorShowCounts"
            />
          </div>
        </template>
        <!-- Tabbed mode -->
        <template v-else>
          <div
            :style="{
              display: 'flex',
              flexShrink: 0,
              borderBottom: '1px solid var(--vj-border, #333333)',
              backgroundColor: 'var(--vj-bg-panel, #252526)',
            }"
          >
            <button
              :style="{
                flex: 1,
                fontSize: '11px',
                padding: '4px 0',
                cursor: 'pointer',
                fontFamily: 'var(--vj-font, monospace)',
                border: 'none',
                background:
                  activePanel === 'tree'
                    ? 'var(--vj-accent-muted, #094771)'
                    : 'transparent',
                color:
                  activePanel === 'tree'
                    ? 'var(--vj-text, #cccccc)'
                    : 'var(--vj-text-muted, #999999)',
              }"
              @click="() => (activePanel = 'tree')"
            >
              Tree
            </button>
            <button
              :style="{
                flex: 1,
                fontSize: '11px',
                padding: '4px 0',
                cursor: 'pointer',
                fontFamily: 'var(--vj-font, monospace)',
                border: 'none',
                background:
                  activePanel === 'form'
                    ? 'var(--vj-accent-muted, #094771)'
                    : 'transparent',
                color:
                  activePanel === 'form'
                    ? 'var(--vj-text, #cccccc)'
                    : 'var(--vj-text-muted, #999999)',
              }"
              @click="() => (activePanel = 'form')"
            >
              Form
            </button>
          </div>
          <div :style="{ flex: 1, minHeight: 0, overflow: 'hidden' }">
            <div
              v-if="activePanel === 'tree'"
              :style="{
                display: 'flex',
                flexDirection: 'column',
                height: '100%',
              }"
            >
              <SearchBar />
              <div :style="{ flex: 1, minHeight: 0, overflow: 'auto' }">
                <TreeView
                  :show-values="props.treeShowValues"
                  :show-counts="props.treeShowCounts"
                />
              </div>
            </div>
            <div
              v-else
              :style="{
                display: 'flex',
                flexDirection: 'column',
                height: '100%',
              }"
            >
              <div :style="{ flex: 1, minHeight: 0 }">
                <FormView
                  :show-descriptions="props.editorShowDescriptions"
                  :show-counts="props.editorShowCounts"
                />
              </div>
            </div>
          </div>
        </template>
      </div>

      <!-- Wide layout -->
      <div
        v-else
        ref="containerRef"
        :style="{ display: 'flex', flex: 1, minHeight: 0 }"
      >
        <div
          :style="{
            flexShrink: 0,
            overflow: 'hidden',
            display: 'flex',
            flexDirection: 'column',
            width: props.sidebarOpen ? sidebarWidth + 'px' : '0',
            transition: 'width 0.2s ease',
          }"
        >
          <SearchBar />
          <div :style="{ flex: 1, minHeight: 0, overflow: 'auto' }">
            <TreeView
              :show-values="props.treeShowValues"
              :show-counts="props.treeShowCounts"
            />
          </div>
        </div>

        <div
          v-if="props.sidebarOpen"
          :style="{
            width: '1px',
            flexShrink: 0,
            backgroundColor: 'var(--vj-border, #333333)',
            position: 'relative',
            transition: 'background-color 0.15s',
          }"
        >
          <div
            :style="{
              position: 'absolute',
              top: 0,
              bottom: 0,
              left: '-3px',
              width: '7px',
              cursor: 'col-resize',
              zIndex: 10,
            }"
            @mousedown="handleMouseDown"
            @mouseenter="
              (e) => {
                const parent = (e.currentTarget as HTMLElement).parentElement;
                if (parent)
                  parent.style.backgroundColor = 'var(--vj-accent, #007acc)';
              }
            "
            @mouseleave="
              (e) => {
                if (!dragging) {
                  const parent = (e.currentTarget as HTMLElement).parentElement;
                  if (parent)
                    parent.style.backgroundColor = 'var(--vj-border, #333333)';
                }
              }
            "
          />
        </div>

        <div
          :style="{
            display: 'flex',
            flexDirection: 'column',
            flex: 1,
            minWidth: 0,
            overflow: 'hidden',
          }"
        >
          <div :style="{ flex: 1, minHeight: 0 }">
            <FormView
              :show-descriptions="props.editorShowDescriptions"
              :show-counts="props.editorShowCounts"
            />
          </div>
        </div>
      </div>
    </VisualJson>
  </div>
</template>

// packages/@visual-json/svelte/src/lib/components/JsonEditor.svelte
<script lang="ts">
	import type { JsonValue, JsonSchema } from '@visual-json/core';
	import { DEFAULT_CSS_VARS } from '@internal/ui';
	import VisualJson from './VisualJson.svelte';
	import TreeView from './TreeView.svelte';
	import FormView from './FormView.svelte';
	import SearchBar from './SearchBar.svelte';

	interface Props {
		value?: JsonValue;
		defaultValue?: JsonValue;
		onChange?: (value: JsonValue) => void;
		schema?: JsonSchema | null;
		height?: string | number;
		width?: string | number;
		class?: string;
		style?: Record<string, string>;
		readOnly?: boolean;
		treeShowValues?: boolean;
		treeShowCounts?: boolean;
		editorShowDescriptions?: boolean;
		editorShowCounts?: boolean;
		sidebarOpen?: boolean;
	}

	let {
		value: valueProp,
		defaultValue,
		onChange,
		schema = null,
		height = '100%',
		width = '100%',
		class: className,
		style: styleProp,
		readOnly = false,
		treeShowValues = true,
		treeShowCounts = false,
		editorShowDescriptions = false,
		editorShowCounts = false,
		sidebarOpen = true
	}: Props = $props();

	const isControlled = valueProp !== undefined;
	let currentValue = $state<JsonValue>(
		isControlled ? (valueProp as JsonValue) : (defaultValue ?? {})
	);
	let editorKey = $state(0);

	$effect(() => {
		const val = valueProp;
		if (isControlled && val !== undefined && val !== currentValue) {
			currentValue = val;
			editorKey++;
		}
	});

	function handleChange(newValue: JsonValue) {
		currentValue = newValue;
		if (!readOnly) {
			onChange?.(newValue);
		}
	}

	// Layout state
	let sidebarWidth = $state(280);
	let isNarrow = $state(false);
	let activePanel = $state<'tree' | 'form'>('tree');
	let containerRef = $state<HTMLDivElement | null>(null);
	let dragging = false;
	let startX = 0;
	let startWidth = 0;

	function checkWidth() {
		if (containerRef) {
			isNarrow = containerRef.offsetWidth < 500;
		}
	}

	$effect(() => {
		checkWidth();
		if (!containerRef) return;
		const observer = new ResizeObserver(checkWidth);
		observer.observe(containerRef);
		return () => observer.disconnect();
	});

	function handleMouseDown(e: MouseEvent) {
		dragging = true;
		startX = e.clientX;
		startWidth = sidebarWidth;
		document.body.style.cursor = 'col-resize';
		document.body.style.userSelect = 'none';

		function handleMouseMove(ev: MouseEvent) {
			if (!dragging) return;
			const delta = ev.clientX - startX;
			sidebarWidth = Math.max(180, Math.min(600, startWidth + delta));
		}

		function handleMouseUp() {
			dragging = false;
			document.body.style.cursor = '';
			document.body.style.userSelect = '';
			document.removeEventListener('mousemove', handleMouseMove);
			document.removeEventListener('mouseup', handleMouseUp);
		}

		document.addEventListener('mousemove', handleMouseMove);
		document.addEventListener('mouseup', handleMouseUp);
	}

	const containerStyle = $derived.by(() => {
		const h = typeof height === 'number' ? `${height}px` : height;
		const w = typeof width === 'number' ? `${width}px` : width;
		const vars = Object.entries(DEFAULT_CSS_VARS)
			.map(([k, v]) => `${k}: ${v}`)
			.join('; ');
		const extra = styleProp
			? Object.entries(styleProp)
					.map(([k, v]) => `${k.replace(/([A-Z])/g, '-$1').toLowerCase()}: ${v}`)
					.join('; ')
			: '';
		return `height: ${h}; width: ${w}; display: flex; flex-direction: column; overflow: hidden; ${vars}; ${extra}`;
	});
</script>

<div data-vj-root="" class={className} style={containerStyle}>
	<style>
		@media (pointer: coarse) {
			[data-vj-root] {
				--vj-input-font-size: 16px;
			}
		}
	</style>
	{#key editorKey}
		<VisualJson value={currentValue} {schema} onchange={handleChange}>
			{#if isNarrow}
				<!-- Narrow layout (< 500px) -->
				<div bind:this={containerRef} style="display: flex; flex-direction: column; flex: 1; min-height: 0;">
					{#if !sidebarOpen}
						<!-- No sidebar: form only -->
						<div style="flex: 1; min-height: 0;">
							<FormView
								showDescriptions={editorShowDescriptions}
								showCounts={editorShowCounts}
							/>
						</div>
					{:else}
						<!-- Tabbed mode -->
						<div
							style="
								display: flex;
								flex-shrink: 0;
								border-bottom: 1px solid var(--vj-border, #333333);
								background-color: var(--vj-bg-panel, #252526);
							"
						>
							<button
								style="
									flex: 1;
									font-size: 11px;
									padding: 4px 0;
									cursor: pointer;
									font-family: var(--vj-font, monospace);
									border: none;
									background: {activePanel === 'tree' ? 'var(--vj-accent-muted, #094771)' : 'transparent'};
									color: {activePanel === 'tree' ? 'var(--vj-text, #cccccc)' : 'var(--vj-text-muted, #999999)'};
								"
								onclick={() => (activePanel = 'tree')}
							>
								Tree
							</button>
							<button
								style="
									flex: 1;
									font-size: 11px;
									padding: 4px 0;
									cursor: pointer;
									font-family: var(--vj-font, monospace);
									border: none;
									background: {activePanel === 'form' ? 'var(--vj-accent-muted, #094771)' : 'transparent'};
									color: {activePanel === 'form' ? 'var(--vj-text, #cccccc)' : 'var(--vj-text-muted, #999999)'};
								"
								onclick={() => (activePanel = 'form')}
							>
								Form
							</button>
						</div>
						<div style="flex: 1; min-height: 0; overflow: hidden;">
							{#if activePanel === 'tree'}
								<div style="display: flex; flex-direction: column; height: 100%;">
									<SearchBar />
									<div style="flex: 1; min-height: 0; overflow: auto;">
										<TreeView showValues={treeShowValues} showCounts={treeShowCounts} />
									</div>
								</div>
							{:else}
								<div style="display: flex; flex-direction: column; height: 100%;">
									<div style="flex: 1; min-height: 0;">
										<FormView
											showDescriptions={editorShowDescriptions}
											showCounts={editorShowCounts}
										/>
									</div>
								</div>
							{/if}
						</div>
					{/if}
				</div>
			{:else}
				<!-- Wide layout -->
				<div bind:this={containerRef} style="display: flex; flex: 1; min-height: 0;">
					<div
						style="
							flex-shrink: 0;
							overflow: hidden;
							display: flex;
							flex-direction: column;
							width: {sidebarOpen ? sidebarWidth + 'px' : '0'};
							transition: width 0.2s ease;
						"
					>
						<SearchBar />
						<div style="flex: 1; min-height: 0; overflow: auto;">
							<TreeView showValues={treeShowValues} showCounts={treeShowCounts} />
						</div>
					</div>

					{#if sidebarOpen}
						<div
							style="
								width: 1px;
								flex-shrink: 0;
								background-color: var(--vj-border, #333333);
								position: relative;
								transition: background-color 0.15s;
							"
						>
							<div
								style="
									position: absolute;
									top: 0;
									bottom: 0;
									left: -3px;
									width: 7px;
									cursor: col-resize;
									z-index: 10;
								"
								onmousedown={handleMouseDown}
								onmouseenter={(e) => {
									const parent = (e.currentTarget as HTMLElement).parentElement;
									if (parent) parent.style.backgroundColor = 'var(--vj-accent, #007acc)';
								}}
								onmouseleave={(e) => {
									if (!dragging) {
										const parent = (e.currentTarget as HTMLElement).parentElement;
										if (parent) parent.style.backgroundColor = 'var(--vj-border, #333333)';
									}
								}}
							></div>
						</div>
					{/if}

					<div style="display: flex; flex-direction: column; flex: 1; min-width: 0; overflow: hidden;">
						<div style="flex: 1; min-height: 0;">
							<FormView
								showDescriptions={editorShowDescriptions}
								showCounts={editorShowCounts}
							/>
						</div>
					</div>
				</div>
			{/if}
		</VisualJson>
	{/key}
</div>
