// packages/@visual-json/svelte/src/components/FormView.svelte
<script lang="ts">
	import { setContext, getContext, tick } from 'svelte';
	import { useStudio } from '../use-studio.js';
	import { useDragDrop } from '../use-drag-drop.svelte.js';
	import { getVisibleNodes, getDisplayKey } from '@internal/ui';
	import { type JsonSchemaProperty } from '@visual-json/core';
	import { deleteSelectedNodes, computeSelectAllIds } from '../selection-utils.js';
	import { FORM_VIEW_KEY, type FormViewContext } from '../form-view-context.js';
	import Breadcrumbs from './Breadcrumbs.svelte';
	import FormField from './FormField.svelte';

	interface Props {
		class?: string;
		showDescriptions?: boolean;
		showCounts?: boolean;
	}

	let { class: className, showDescriptions = false, showCounts = false }: Props = $props();

	const { state: studioState, actions } = useStudio();

	let containerRef = $state<HTMLDivElement | null>(null);
	let isFocused = $state(false);
	let editingNodeId = $state<string | null>(null);
	let collapsedIds = $state<Set<string>>(new Set());
	let preEditTree = studioState.tree;

	const displayNode = $derived(
		(studioState.drillDownNodeId
			? studioState.tree.nodesById.get(studioState.drillDownNodeId)
			: null) ?? studioState.tree.root
	);

	// Reset form state when display node changes
	$effect(() => {
		displayNode.id;
		editingNodeId = null;
		collapsedIds = new Set();
	});

	const visibleNodes = $derived(
		getVisibleNodes(displayNode, (id) => !collapsedIds.has(id))
	);

	const { dragState, handleDragStart, handleDragOver, handleDragEnd, handleDrop } = useDragDrop(
		() => visibleNodes,
		() => studioState.selectedNodeIds
	);

	// Override visible nodes for range selection
	$effect(() => {
		actions.setVisibleNodesOverride(visibleNodes);
		return () => actions.setVisibleNodesOverride(null);
	});

	const metrics = $derived.by(() => {
		let maxKey = 1;
		let maxD = 0;
		const baseSegments =
			displayNode.path === '/'
				? 0
				: displayNode.path.split('/').filter(Boolean).length;
		for (const node of visibleNodes) {
			const keyText = node.parentId === null ? '/' : getDisplayKey(node, studioState.tree);
			if (keyText.length > maxKey) maxKey = keyText.length;
			const segments =
				node.path === '/' ? 0 : node.path.split('/').filter(Boolean).length;
			const depth = segments - baseSegments;
			if (depth > maxD) maxD = depth;
		}
		return { maxKeyLength: maxKey, maxDepth: maxD };
	});

	const schema = $derived(studioState.schema);
	const rootSchema = $derived<JsonSchemaProperty | undefined>(studioState.schema ?? undefined);

	function onSelect(nodeId: string, e: MouseEvent) {
		editingNodeId = null;
		if (e.shiftKey) {
			actions.setVisibleNodesOverride(visibleNodes);
			actions.selectNodeRange(nodeId);
		} else if (e.metaKey || e.ctrlKey) {
			actions.toggleNodeSelection(nodeId);
		} else {
			actions.selectNode(nodeId);
		}
	}

	function onToggleCollapse(nodeId: string) {
		const next = new Set(collapsedIds);
		if (next.has(nodeId)) next.delete(nodeId);
		else next.add(nodeId);
		collapsedIds = next;
	}

	function onStartEditing(nodeId: string) {
		preEditTree = studioState.tree;
		editingNodeId = nodeId;
	}

	function scrollToNode(nodeId: string) {
		requestAnimationFrame(() => {
			const el = containerRef?.querySelector(`[data-form-node-id="${nodeId}"]`);
			el?.scrollIntoView({ block: 'nearest' });
		});
	}

	function handleKeyDown(e: KeyboardEvent) {
		if (editingNodeId) {
			if (e.key === 'Escape') {
				e.preventDefault();
				e.stopPropagation();
				actions.setTree(preEditTree);
				editingNodeId = null;
				containerRef?.focus();
			} else if (e.key === 'Enter') {
				e.preventDefault();
				e.stopPropagation();
				editingNodeId = null;
				containerRef?.focus();
			}
			return;
		}

		let currentIndex = visibleNodes.findIndex((n) => n.id === studioState.focusedNodeId);
		if (currentIndex === -1 && visibleNodes.length > 0) currentIndex = 0;

		switch (e.key) {
			case 'ArrowDown': {
				e.preventDefault();
				const next = visibleNodes[currentIndex + 1];
				if (next) {
					if (e.shiftKey) {
						actions.setVisibleNodesOverride(visibleNodes);
						actions.selectNodeRange(next.id);
					} else {
						actions.selectNode(next.id);
					}
					scrollToNode(next.id);
				}
				break;
			}
			case 'ArrowUp': {
				e.preventDefault();
				const prev = visibleNodes[currentIndex - 1];
				if (prev) {
					if (e.shiftKey) {
						actions.setVisibleNodesOverride(visibleNodes);
						actions.selectNodeRange(prev.id);
					} else {
						actions.selectNode(prev.id);
					}
					scrollToNode(prev.id);
				}
				break;
			}
			case 'ArrowRight': {
				e.preventDefault();
				const node = currentIndex >= 0 ? visibleNodes[currentIndex] : null;
				if (node && (node.type === 'object' || node.type === 'array')) {
					if (collapsedIds.has(node.id)) {
						const next = new Set(collapsedIds);
						next.delete(node.id);
						collapsedIds = next;
					} else if (node.children.length > 0) {
						actions.selectNode(node.children[0].id);
						scrollToNode(node.children[0].id);
					}
				}
				break;
			}
			case 'ArrowLeft': {
				e.preventDefault();
				const current = currentIndex >= 0 ? visibleNodes[currentIndex] : null;
				if (!current) break;
				const isNodeContainer = current.type === 'object' || current.type === 'array';
				if (isNodeContainer && !collapsedIds.has(current.id)) {
					const next = new Set(collapsedIds);
					next.add(current.id);
					collapsedIds = next;
				} else if (current.parentId) {
					const parentInVisible = visibleNodes.find((n) => n.id === current.parentId);
					if (parentInVisible) {
						actions.selectNode(parentInVisible.id);
						scrollToNode(parentInVisible.id);
					}
				}
				break;
			}
			case 'Enter': {
				e.preventDefault();
				if (studioState.focusedNodeId) {
					preEditTree = studioState.tree;
					actions.selectNode(studioState.focusedNodeId);
					editingNodeId = studioState.focusedNodeId;
				}
				break;
			}
			case 'a': {
				if (e.metaKey || e.ctrlKey) {
					e.preventDefault();
					const ids = computeSelectAllIds(
						studioState.tree,
						studioState.focusedNodeId,
						studioState.selectedNodeIds
					);
					if (ids) {
						actions.setSelection(studioState.focusedNodeId, ids, studioState.focusedNodeId);
					}
				}
				break;
			}
			case 'Escape': {
				e.preventDefault();
				if (studioState.selectedNodeIds.size > 1 && studioState.focusedNodeId) {
					actions.selectNode(studioState.focusedNodeId);
				} else {
					actions.setSelection(null, new Set(), null);
				}
				break;
			}
			case 'Delete':
			case 'Backspace': {
				e.preventDefault();
				const { newTree, nextFocusId } = deleteSelectedNodes(
					studioState.tree,
					studioState.selectedNodeIds,
					visibleNodes
				);
				if (newTree === studioState.tree) break;
				actions.setTree(newTree);
				if (nextFocusId) {
					actions.selectNode(nextFocusId);
				} else {
					actions.setSelection(null, new Set(), null);
				}
				break;
			}
		}
	}

	const formCtx: FormViewContext = {
		get schema() { return schema; },
		get rootSchema() { return rootSchema; },
		get showDescriptions() { return showDescriptions; },
		get showCounts() { return showCounts; },
		get editingNodeId() { return editingNodeId; },
		get collapsedIds() { return collapsedIds; },
		get maxKeyLength() { return metrics.maxKeyLength; },
		get maxDepth() { return metrics.maxDepth; },
		get isFocused() { return isFocused; },
		get dragState() { return dragState; },
		onSelect,
		onToggleCollapse,
		onStartEditing,
		onDragStart: handleDragStart,
		onDragOver: handleDragOver,
		onDragEnd: handleDragEnd,
		onDrop: handleDrop
	};

	setContext(FORM_VIEW_KEY, formCtx);
</script>

<div
	class={className}
	style="
		background-color: var(--vj-bg, #1e1e1e);
		color: var(--vj-text, #cccccc);
		height: 100%;
		font-family: var(--vj-font, monospace);
		display: flex;
		flex-direction: column;
	"
>
	<div
		style="
			display: flex;
			align-items: center;
			padding: 4px 8px;
			border-bottom: 1px solid var(--vj-border, #333333);
			background-color: var(--vj-bg, #1e1e1e);
			flex-shrink: 0;
		"
	>
		<Breadcrumbs />
	</div>
	<div
		bind:this={containerRef}
		data-form-container
		role="tree"
		tabindex="0"
		style="flex: 1; overflow: auto; outline: none;"
		onkeydown={handleKeyDown}
		onfocus={() => (isFocused = true)}
		onblur={(e) => {
			if (!(e.currentTarget as HTMLElement).contains(e.relatedTarget as Node)) {
				isFocused = false;
			}
		}}
	>
		<FormField node={displayNode} depth={0} />
	</div>
</div>

// packages/@visual-json/vue/src/components/FormView.vue
<script setup lang="ts">
import {
  shallowRef,
  computed,
  watch,
  provide,
  onMounted,
  onUnmounted,
} from "vue";
import type { JsonSchemaProperty } from "@visual-json/core";
import { useStudio } from "../composables/use-studio";
import { useDragDrop } from "../composables/use-drag-drop";
import { getVisibleNodes, getDisplayKey } from "@internal/ui";
import { deleteSelectedNodes, computeSelectAllIds } from "../selection-utils";
import { FORM_VIEW_KEY } from "./form-view-context";
import Breadcrumbs from "./Breadcrumbs.vue";
import FormField from "./FormField.vue";

const props = withDefaults(
  defineProps<{
    class?: string;
    showDescriptions?: boolean;
    showCounts?: boolean;
  }>(),
  { showDescriptions: false, showCounts: false },
);

const { state, actions } = useStudio();

const containerRef = shallowRef<HTMLDivElement | null>(null);
const isFocused = shallowRef(false);
const editingNodeId = shallowRef<string | null>(null);
const collapsedIds = shallowRef<Set<string>>(new Set());
let preEditTree = state.tree.value;

const displayNode = computed(() => {
  const drillDownNode = state.drillDownNodeId.value
    ? state.tree.value.nodesById.get(state.drillDownNodeId.value)
    : null;
  return drillDownNode ?? state.tree.value.root;
});

// Reset form state when display node changes
watch(
  () => displayNode.value.id,
  () => {
    editingNodeId.value = null;
    collapsedIds.value = new Set();
  },
);

const visibleNodes = computed(() =>
  getVisibleNodes(displayNode.value, (id) => !collapsedIds.value.has(id)),
);

const {
  dragState,
  handleDragStart,
  handleDragOver,
  handleDragEnd,
  handleDrop,
} = useDragDrop(visibleNodes, state.selectedNodeIds);

// Override visible nodes for range selection in form view
onMounted(() => {
  actions.setVisibleNodesOverride(visibleNodes.value);
});
onUnmounted(() => {
  actions.setVisibleNodesOverride(null);
});
watch(visibleNodes, (nodes) => {
  actions.setVisibleNodesOverride(nodes);
});

const metrics = computed(() => {
  let maxKey = 1;
  let maxD = 0;
  const baseSegments =
    displayNode.value.path === "/"
      ? 0
      : displayNode.value.path.split("/").filter(Boolean).length;
  for (const node of visibleNodes.value) {
    const keyText =
      node.parentId === null ? "/" : getDisplayKey(node, state.tree.value);
    if (keyText.length > maxKey) maxKey = keyText.length;
    const segments =
      node.path === "/" ? 0 : node.path.split("/").filter(Boolean).length;
    const depth = segments - baseSegments;
    if (depth > maxD) maxD = depth;
  }
  return { maxKeyLength: maxKey, maxDepth: maxD };
});

const maxKeyLength = computed(() => metrics.value.maxKeyLength);
const maxDepth = computed(() => metrics.value.maxDepth);

const schema = computed(() => state.schema.value);
const rootSchema = computed<JsonSchemaProperty | undefined>(
  () => state.schema.value ?? undefined,
);

function onSelect(nodeId: string, e: MouseEvent) {
  editingNodeId.value = null;
  if (e.shiftKey) {
    actions.setVisibleNodesOverride(visibleNodes.value);
    actions.selectNodeRange(nodeId);
  } else if (e.metaKey || e.ctrlKey) {
    actions.toggleNodeSelection(nodeId);
  } else {
    actions.selectNode(nodeId);
  }
}

function onToggleCollapse(nodeId: string) {
  const next = new Set(collapsedIds.value);
  if (next.has(nodeId)) next.delete(nodeId);
  else next.add(nodeId);
  collapsedIds.value = next;
}

function onStartEditing(nodeId: string) {
  preEditTree = state.tree.value;
  editingNodeId.value = nodeId;
}

function scrollToNode(nodeId: string) {
  requestAnimationFrame(() => {
    const el = containerRef.value?.querySelector(
      `[data-form-node-id="${nodeId}"]`,
    );
    el?.scrollIntoView({ block: "nearest" });
  });
}

function handleKeyDown(e: KeyboardEvent) {
  if (editingNodeId.value) {
    if (e.key === "Escape") {
      e.preventDefault();
      e.stopPropagation();
      actions.setTree(preEditTree);
      editingNodeId.value = null;
      containerRef.value?.focus();
    } else if (e.key === "Enter") {
      e.preventDefault();
      e.stopPropagation();
      editingNodeId.value = null;
      containerRef.value?.focus();
    }
    return;
  }

  let currentIndex = visibleNodes.value.findIndex(
    (n) => n.id === state.focusedNodeId.value,
  );
  if (currentIndex === -1 && visibleNodes.value.length > 0) {
    currentIndex = 0;
  }

  switch (e.key) {
    case "ArrowDown": {
      e.preventDefault();
      const next = visibleNodes.value[currentIndex + 1];
      if (next) {
        if (e.shiftKey) {
          actions.setVisibleNodesOverride(visibleNodes.value);
          actions.selectNodeRange(next.id);
        } else {
          actions.selectNode(next.id);
        }
        scrollToNode(next.id);
      }
      break;
    }
    case "ArrowUp": {
      e.preventDefault();
      const prev = visibleNodes.value[currentIndex - 1];
      if (prev) {
        if (e.shiftKey) {
          actions.setVisibleNodesOverride(visibleNodes.value);
          actions.selectNodeRange(prev.id);
        } else {
          actions.selectNode(prev.id);
        }
        scrollToNode(prev.id);
      }
      break;
    }
    case "ArrowRight": {
      e.preventDefault();
      const node = currentIndex >= 0 ? visibleNodes.value[currentIndex] : null;
      if (node && (node.type === "object" || node.type === "array")) {
        if (collapsedIds.value.has(node.id)) {
          const next = new Set(collapsedIds.value);
          next.delete(node.id);
          collapsedIds.value = next;
        } else if (node.children.length > 0) {
          actions.selectNode(node.children[0].id);
          scrollToNode(node.children[0].id);
        }
      }
      break;
    }
    case "ArrowLeft": {
      e.preventDefault();
      const current =
        currentIndex >= 0 ? visibleNodes.value[currentIndex] : null;
      if (!current) break;
      const isContainer = current.type === "object" || current.type === "array";
      if (isContainer && !collapsedIds.value.has(current.id)) {
        const next = new Set(collapsedIds.value);
        next.add(current.id);
        collapsedIds.value = next;
      } else if (current.parentId) {
        const parentInVisible = visibleNodes.value.find(
          (n) => n.id === current.parentId,
        );
        if (parentInVisible) {
          actions.selectNode(parentInVisible.id);
          scrollToNode(parentInVisible.id);
        }
      }
      break;
    }
    case "Enter": {
      e.preventDefault();
      if (state.focusedNodeId.value) {
        preEditTree = state.tree.value;
        actions.selectNode(state.focusedNodeId.value);
        editingNodeId.value = state.focusedNodeId.value;
      }
      break;
    }
    case "a": {
      if (e.metaKey || e.ctrlKey) {
        e.preventDefault();
        const ids = computeSelectAllIds(
          state.tree.value,
          state.focusedNodeId.value,
          state.selectedNodeIds.value,
        );
        if (ids) {
          actions.setSelection(
            state.focusedNodeId.value,
            ids,
            state.focusedNodeId.value,
          );
        }
      }
      break;
    }
    case "Escape": {
      e.preventDefault();
      if (state.selectedNodeIds.value.size > 1 && state.focusedNodeId.value) {
        actions.selectNode(state.focusedNodeId.value);
      } else {
        actions.setSelection(null, new Set<string>(), null);
      }
      break;
    }
    case "Delete":
    case "Backspace": {
      e.preventDefault();
      const { newTree, nextFocusId } = deleteSelectedNodes(
        state.tree.value,
        state.selectedNodeIds.value,
        visibleNodes.value,
      );
      if (newTree === state.tree.value) break;
      actions.setTree(newTree);
      if (nextFocusId) {
        actions.selectNode(nextFocusId);
      } else {
        actions.setSelection(null, new Set<string>(), null);
      }
      break;
    }
  }
}

provide(FORM_VIEW_KEY, {
  schema,
  rootSchema,
  showDescriptions: props.showDescriptions,
  showCounts: props.showCounts,
  editingNodeId,
  collapsedIds,
  maxKeyLength,
  maxDepth,
  isFocused,
  dragState,
  onSelect,
  onToggleCollapse,
  onStartEditing,
  onDragStart: handleDragStart,
  onDragOver: handleDragOver,
  onDragEnd: handleDragEnd,
  onDrop: handleDrop,
});
</script>

<template>
  <div
    :style="{
      backgroundColor: 'var(--vj-bg, #1e1e1e)',
      color: 'var(--vj-text, #cccccc)',
      height: '100%',
      fontFamily: 'var(--vj-font, monospace)',
      display: 'flex',
      flexDirection: 'column',
    }"
  >
    <div
      :style="{
        display: 'flex',
        alignItems: 'center',
        padding: '4px 8px',
        borderBottom: '1px solid var(--vj-border, #333333)',
        backgroundColor: 'var(--vj-bg, #1e1e1e)',
        flexShrink: 0,
      }"
    >
      <Breadcrumbs />
    </div>
    <div
      ref="containerRef"
      data-form-container
      tabindex="0"
      :style="{
        flex: 1,
        overflow: 'auto',
        outline: 'none',
      }"
      @keydown="handleKeyDown"
      @focus="() => (isFocused = true)"
      @blur="
        (e) => {
          if (
            !(e.currentTarget as HTMLElement).contains(e.relatedTarget as Node)
          ) {
            isFocused = false;
          }
        }
      "
    >
      <FormField :node="displayNode" :depth="0" />
    </div>
  </div>
</template>
